### ISSUE TITLE
find_free_ports() returning empty list in RHEL host

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado#3349] opened 2019-10-25 05:11 UTC
find_free_ports(),https://github.com/avocado-framework/avocado/blob/master/avocado/utils/network.py#L89,  by-default returns none on RHEL8 host with `address=localhost` [1] but the same works fine with explicitly pass `address=127.0.0.1` [2]

could not find any issues in host network files[3], all seems fine, any help would be appreciated, Thanks in advance.

[1]
```
# python
Python 3.6.8 (default, Oct 11 2019, 10:45:08) 
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import network
>>> network.find_free_ports(5000,6000,1)
[]
```

[2]
```
>>> network.find_free_ports(5000,6000,1, address='127.0.0.1')
[5364]
>>> 
```

[3]
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
...
....
```

**Comment by beraldoleal** [comment] 2019-10-28 18:46
Hi @sathnaga , I'm not sure if the function signature has changed but, here I have the following order:

```
def find_free_port(start_port=1024, end_port=65535, address="localhost", sequent=False):
```

So in your first call, you are trying to put `1` on `address`.

If you call with the correct order, it will give the same result with localhost or 127.0.0.1:

```
In [2]: network.find_free_port(start_port=5000, end_port=6000, sequent=True, address='127.0.0.1')                      
Out[2]: 5000

In [3]: network.find_free_port(start_port=5000, end_port=6000, sequent=True, address='localhost')                      
Out[3]: 5000
```
Can you please double check?

**Comment by apahim** [comment] 2019-10-29 13:01
Not related, but looking at the `find_free_ports()` and the `find_free_port()` I see a lot of code duplication. Whoever is going to tackle this, please use the opportunity to refactor the code removing the duplication ;)

**Comment by clebergnu** [comment] 2019-10-29 16:02
I could not reproduce this:

```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.0 (Ootpa)
$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

Avocado commit:

```
$ git show | head -1
commit f1cdf81284e01ae2c20b2392b1e3718aefbeec2c
```

```
$ python3 
Python 3.6.8 (default, Jan 11 2019, 02:17:16) 
[GCC 8.2.1 20180905 (Red Hat 8.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import network
>>> network.find_free_ports(5000, 6000, 1)
[5356]
>>> network.find_free_ports(5000, 6000, 1, address='localhost')
[5855]
>>> network.find_free_ports(5000, 6000, 1, address='127.0.0.1')
[5723]
```

**Comment by beraldoleal** [comment] 2019-10-29 17:39
I could not reproduce it either in Fedora or RHEL 8.

I got the same results as @clebergnu.

**Comment by sathnaga** [comment] 2019-10-30 06:11
> I could not reproduce this:
> 
> ```
> $ cat /etc/redhat-release 
> Red Hat Enterprise Linux release 8.0 (Ootpa)
> $ cat /etc/hosts
> 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
> ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
> ```
> 
> Avocado commit:
> 
> ```
> $ git show | head -1
> commit f1cdf81284e01ae2c20b2392b1e3718aefbeec2c
> ```
> 
> ```
> $ python3 
> Python 3.6.8 (default, Jan 11 2019, 02:17:16) 
> [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from avocado.utils import network
> >>> network.find_free_ports(5000, 6000, 1)
> [5356]
> >>> network.find_free_ports(5000, 6000, 1, address='localhost')
> [5855]
> >>> network.find_free_ports(5000, 6000, 1, address='127.0.0.1')
> [5723]
> ```

Strange, not sure what else is missing in my environment, am using RHEL8.1 env.

**Comment by willianrampazzo** [comment] 2020-06-23 19:56
The `network.py` module had a big refactor some time ago. I'm closing this issue. If it is still valid, feel free to reopen.

**Closed by willianrampazzo** 2020-06-23 19:56 UTC
