### ISSUE TITLE
selftests/safeloader.sh fails in pre-release tests

### ISSUE THREAD

**Issue by ana** [avocado-framework/avocado#5368] opened 2022-05-02 13:52 UTC
The safeloader script has been failing for 3 weeks in the pre-release tests, see:
https://github.com/avocado-framework/avocado/runs/6252641446?check_suite_focus=true

Log output: 
```
2022-05-02T05:36:15.4686337Z RESULTS    : PASS 1074 | ERROR 0 | FAIL 1 | SKIP 57 | WARN 0 | INTERRUPT 0 | CANCEL 2
2022-05-02T05:36:15.7280055Z JOB HTML   : /home/runner/avocado/job-results/job-2022-05-02T05.22-a62d2e7/results.html
2022-05-02T05:36:15.8113991Z JOB TIME   : 810.38 s
2022-05-02T05:36:15.8178547Z Log file "debug.log" content for test "static-checks-2-selftests/safeloader.sh" (FAIL):
2022-05-02T05:36:15.8180281Z selftests/safeloader.sh: FAIL
2022-05-02T05:36:15.8180688Z [stdout] *** Checking safeloader on selftests/unit/test_dependencies_resolver.py ***
2022-05-02T05:36:15.8181393Z [stdout] *** Checking safeloader on selftests/unit/test_dispatcher.py ***
2022-05-02T05:36:15.8182252Z [stdout] *** Checking safeloader on selftests/unit/test_hintfiles.py ***
2022-05-02T05:36:15.8182841Z [stdout] *** Checking safeloader on selftests/unit/test_parameters.py ***
2022-05-02T05:36:15.8183839Z [stdout] *** Checking safeloader on selftests/unit/test_parser.py ***
2022-05-02T05:36:15.8184493Z [stdout] *** Checking safeloader on selftests/unit/test_plugin_interfaces.py ***
2022-05-02T05:36:15.8185323Z [stdout] *** Checking safeloader on selftests/unit/test_result.py ***
2022-05-02T05:36:15.8185900Z [stdout] *** Checking safeloader on selftests/unit/test_runner_asset.py ***
2022-05-02T05:36:15.8186660Z [stderr] Traceback (most recent call last):
2022-05-02T05:36:15.8187489Z [stderr]   File "/home/runner/work/avocado/avocado/contrib/scripts/find-python-unittest", line 51, in <module>
2022-05-02T05:36:15.8188366Z [stderr]     suite = loader.discover(start_dir, pattern)
2022-05-02T05:36:15.8189154Z [stderr]   File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/unittest/loader.py", line 349, in discover
2022-05-02T05:36:15.8190015Z [stderr]     tests = list(self._find_tests(start_dir, pattern))
2022-05-02T05:36:15.8190645Z [stderr]   File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/unittest/loader.py", line 405, in _find_tests
2022-05-02T05:36:15.8191479Z [stderr]     tests, should_recurse = self._find_test_path(
2022-05-02T05:36:15.8192081Z [stderr]   File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/unittest/loader.py", line 458, in _find_test_path
2022-05-02T05:36:15.8192921Z [stderr]     raise ImportError(
2022-05-02T05:36:15.8193822Z [stderr] ImportError: 'test_runner_asset' module incorrectly imported from '/home/runner/work/avocado/avocado/selftests/functional'. Expected '/home/runner/work/avocado/avocado/selftests/unit'. Is this module globally installed?

```

I have reproduced this problem in a fresh system with the following steps:

```
git clone https://github.com/avocado-framework/avocado.git
pip install -r requirements-dev.txt
python3 setup.py develop
make check
```

**Comment by clebergnu** [comment] 2022-11-28 17:59
Closing as a duplicate of https://github.com/avocado-framework/avocado/issues/5378

**Closed by clebergnu** 2022-11-28 17:59 UTC
Labels: bug
