### ISSUE TITLE
Avocado crashed: RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by amitkrout** [avocado-framework/avocado#1551] opened 2016-10-20 06:46 UTC
Environment : 

```
System Version: OS X 10.11.6 (15G31)
Kernel Version: Darwin 15.6.0
Avocado 36.0lts
```

Steps to reproduce:

```
1. Download latest CDK + virtualbox provider on mac 
2. Go to the directory "/cdk/components/rhel/rhel-ose" and execute "vagrant up"  
2. Clone  "https://github.com/projectatomic/adb-tests" and modify the config.yaml 
    vagrant_VAGRANTFILE_DIR : "/cdk/components/rhel/rhel-ose"
     vagrant_PROVIDER : "virtualbox"
     vagrant_RHN_USERNAME : "usename"
     vagrant_RHN_PASSWORD : "password"
     openshift_lib_MODULE : "/adb-tests/cdk-testsuite/libraries/openshift/openshift.py"
     openshift_util_MODULE : "/adb-tests/cdk-testsuite/utils/openshiftUtils.py"
3. Go to the directory "/adb-tests/cdk-testsuite/tests" and execute the command 
    "avocado run openshiftSanity.py -m ../config/config.yaml"
```

Error : 

```
Traceback (most recent call last):

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/job.py", line 515, in _run
    self.args.test_result_total)

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/runner.py", line 470, in run_suite
    summary, deadline)

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/runner.py", line 306, in run_test
    proc.start()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/forking.py", line 126, in __init__
    code = process_obj._bootstrap()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 274, in _bootstrap
    sys.stderr.write('Process %s:\n' % self.name)

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/output.py", line 612, in write
    self._flush_buffer()

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/output.py", line 636, in _flush_buffer
    self._log_line(''.join(self._buffer))

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/output.py", line 632, in _log_line
    lg.log(self._level, self._prefix + line)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1229, in log
    self._log(level, msg, args, **kwargs)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1284, in _log
    self.handle(record)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1294, in handle
    self.callHandlers(record)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1341, in callHandlers
    " \"%s\"\n" % self.name)

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/output.py", line 612, in write
    self._flush_buffer()

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/output.py", line 636, in _flush_buffer
    self._log_line(''.join(self._buffer))
.
.
.
File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/output.py", line 612, in write
    self._flush_buffer()

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/output.py", line 636, in _flush_buffer
    self._log_line(''.join(self._buffer))

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/output.py", line 632, in _log_line
    lg.log(self._level, self._prefix + line)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1229, in log
    self._log(level, msg, args, **kwargs)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1284, in _log
    self.handle(record)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1294, in handle
    self.callHandlers(record)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1341, in callHandlers
    " \"%s\"\n" % self.name)

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/output.py", line 612, in write
    self._flush_buffer()

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/output.py", line 636, in _flush_buffer
    self._log_line(''.join(self._buffer))

  File "/Library/Python/2.7/site-packages/avocado-36.0lts-py2.7.egg/avocado/core/output.py", line 632, in _log_line
    lg.log(self._level, self._prefix + line)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1229, in log
    self._log(level, msg, args, **kwargs)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1283, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1257, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
```

**Comment by ldoktor** [comment] 2016-10-21 10:44
Hello @amitkrout, before going deeper, I'd like to know, whether is this reproducible on x86_64 on linux, or whether is this only in OS X problem. If so, does the example tests run? (Mac was never tested, we only did some Windows experimental runs, but it was never a priority).

**Comment by ldoktor** [comment] 2016-10-21 11:05
Btw I looked at the `openshiftSanity` test and I can offer some improvements, if you want to. Mainly about the structure, the use of `setUp` and `tearDown`, maybe advertise an `aexpect` instead of `pexpect` and so on. Feel free to contact me via email (I won't send any patches, I don't have time for that, but I can offer advice)

**Comment by amitkrout** [comment] 2016-10-24 06:32
@idoktor Till now i have not found any issue on linux except OS X. Thanks for the suggestion of improvement. My question is what can be achieved if ```aexpect``` is used instead of ```pexpect``` and so on ? or is it a workaround to make the code run on OS X if yes please add your suggestion. Will implement it.

**Comment by ldoktor** [comment] 2016-10-24 15:16
OK, unfortunately I don't have a Mac to try it out. Does simple `avocado run passtest.py` works well (if you have example tests installed)? Can you try downloading the example tests and run them to see whether the problem is related to your suite or not.

I sent you an email (hopefully to the right address) with some remarks, if you sent me credentials to some mac machine I'll take a look at it (although again, we don't support Mac officially, so it won't be a high priority).

**Comment by ldoktor** [comment] 2016-10-29 12:03
Dear @amitkrout, I tried to reproduce it on your machine, nor I could find any existing job with this traceback in it. Anyway based on the traceback I can tell that there was a logging stream which included the `sys.stderr`. The problem is, that the `multiprocessing.process` library wrote something into the `sys.stderr` and the `sys.stderr` forwarded this message to the `logging`. `logging` then attempted to log the same message to one of it's handlers, which contained `sys.stderr`. Now we have the circle.

I can't tell what happened, I tried many things and was unable to reproduce it in avocado. I can reproduce it easily with pure python, thought:

```python
import logging
from avocado.core import output

logging.basicConfig(level=0)

stderr=output.LoggingFile()
logging.getLogger("").addHandler(logging.StreamHandler(stderr))
stderr.write("adsf\n")
```

This is an incorrect usage, so the infinite recursion is actually expected. The big question is how did the `stderr` ended up in `logging`. Is it possible that one of your tests (or library) might have altered the logging/sys.stderr? I single-stepped avocado and I can't see how this could happen.

Another question, do you use `avocado --show` or `avocado run --store-logging-stream`? (I haven't investigated those deeply while playing with the reproducer and they affect logging. So I'm just trying to minimize the options here).

Also if you find the actual job where it crashed, could you please send it to me (eg. via email)

**Comment by ldoktor** [comment] 2016-11-04 09:57
The same error now occurred in travis: https://travis-ci.org/avocado-framework/avocado/jobs/173195490#L1254 so let's increase the priority.

**Comment by apahim** [comment] 2016-11-24 14:42
@amitkrout, could you please check if this Pull Request fixes the issue for you? https://github.com/avocado-framework/avocado/pull/1631

**Comment by ldoktor** [comment] 2016-12-01 18:25
Hello @amitkrout, the problem should be fixed in master https://github.com/avocado-framework/avocado/pull/1652 , we'll also backport it to 36.lts. Just for the record, there is a simple reproducer described here: https://github.com/avocado-framework/avocado/pull/1644#discussion_r89829228

**Closed by ldoktor** 2016-12-01 18:25 UTC
