### ISSUE TITLE
selftests/signedoff-check.sh false positive on GH Actions CI job

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#5670] opened 2023-04-27 22:15 UTC
**Describe the bug**
A commit without a `Signed-off-by` can result in a successful pass when checked with `selftests/signedoff-check.sh` on GH Actions.

**Steps to reproduce**
Send a PR with a commit without a `Signed-off-by` line and let the CI jobs run.

One example is [here](https://github.com/avocado-framework/avocado/actions/runs/4762040395/jobs/8591248619?pr=5653#step:8:22).

**Expected behavior**
Commits without `Signed-off-by` line should trigger a failure, no matter where they are run.

**Current behavior**
The test passes on GH Actions CI Jobs, but fails at my local system.

**System information (please complete the following information):**
 - OS: `LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 37 (Thirty Seven)
Release:	37
Codename:	ThirtySeven`
 - Avocado version: `a8e630e03cbc923cf4c0dcb84171db0d5fa67ac3` from https://github.com/avocado-framework/avocado/pull/5653
 - Avocado installation method: `make develop`

**Additional information**
Add any other information about the problem here. Test details can be added here.

**Comment by richtja** [comment] 2023-05-09 09:48
Hi @clebergnu, I did a couple of tests on [GH Actions](https://github.com/richtja/avocado/actions/workflows/ci.yml) and I am unable to reproduce this. It looks like `signedoff-check.sh` works correctly in GH Actions.

**Comment by PaulYuuu** [comment] 2023-05-18 03:21
Currently, the checkout step is:
```
jobs:
  static-checks:

    name: Static checks
    runs-on: ubuntu-20.04
    container:
      image: quay.io/avocado-framework/avocado-ci-fedora-36

    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event on branch is ${{ github.ref }} in repository is ${{ github.repository }}, runner on ${{ runner.os }}"
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

I also meet a similar issue, please see: https://github.com/autotest/tp-qemu/pull/3668#discussion_r1188058524, finally I add `ref: ${{ github.event.pull_request.head.sha }}`. Without this, the git operation is "git rebase", with this, it's "git merge" I guess.

So if the commit date is too old, and we have some commits merged after that commit date, the latest commit is not the patch commit. Just share some info, you can have a try.

BTW, if the PR contains more than 1 commit, the current CI check only check the last one. This is addressed in tp-qemu: https://github.com/autotest/tp-qemu/pull/3668, which also includes some other checks.

**Comment by PaulYuuu** [comment] 2023-05-18 03:29
The example in the description, the checkout steps are:(last commit date: `Date:   Mon Mar 20 14:32:14 2023 +0530`)
```
git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/* +8d06abd0e2bffde897e955530229266106c5b49a:refs/remotes/pull/5653/merge
git checkout --progress --force refs/remotes/pull/5653/merge
git log --no-merges -1
commit 24801655e6c74cb8e5ea457b403e35b9af843afa
Author: Naresh Bannoth <nbannoth@in.ibm.com>
Date:   Mon Mar 20 14:32:14 2023 +0530

    Changing the script to get the exact active controller_id in nvme.py

    currently we are using the 0] string to get the controller id in list_ctrl option.
    This may not give always the active controller ID of nvme adapter among the two
    IDs it holds. So changing the nvme option to id-ctrl and finding with exact
    controller_id string.

    Signed-off-by: Naresh Bannoth <nbannoth@in.ibm.com>
```

The commit we want is: (commit date `Date:   Tue Apr 18 15:05:48 2023 +0800`)
```
commit a8e630e03cbc923cf4c0dcb84171db0d5fa67ac3
Author: mataotao <mataotao@uniontech.com>
Date:   Tue Apr 18 15:05:48 2023 +0800

    Modify the CHECK_FILE_CONTAINS and CHECK_VERSION_REGEX fields of UnionTechProbe
```

**Comment by PaulYuuu** [comment] 2023-05-25 09:46
Hello, I see you are doing some tests, here I want to share more info to you. Commit have 2 dates, AuthorDate and CommitDate. Date in git log is **AuthorDate**, here is the diff in your test branch and https://github.com/avocado-framework/avocado/pull/5653, CommitDate of your commit in test branch is the newest one.

```git
git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/* +f5a45b725760a951adb16c1df888d7f4604d678c:refs/remotes/pull/5692/merge
git checkout --progress --force refs/remotes/pull/5692/merge
git log --no-merges --pretty=fuller -2
commit fd3b15f3e9bbf6d957793677843e0d6e67399c3f
Author:     Jan Richter <jarichte@redhat.com>
AuthorDate: Fri May 5 16:58:35 2023 +0200
Commit:     Jan Richter <jarichte@redhat.com>
CommitDate: Thu May 25 10:24:57 2023 +0200

     Modify the CHECK_FILE_CONTAINS and CHECK_VERSION_REGEX fields of UnionTechProbe

commit f89b7176a8a6ad3c16124ea76c02fc4e60057bc7
Author:     Cleber Rosa <crosa@redhat.com>
AuthorDate: Wed May 24 10:13:07 2023 -0400
Commit:     Cleber Rosa <crosa@redhat.com>
CommitDate: Wed May 24 10:13:07 2023 -0400

    Packit: update list of chroots as supported by COPR

    COPR no longer supports fedora-36, as can be seen by:

     $ copr-cli list-chroots

    Let's bump the Fedora versions used for alternative architectures.

    Signed-off-by: Cleber Rosa <crosa@redhat.com>
```

```
git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/* +8d06abd0e2bffde897e955530229266106c5b49a:refs/remotes/pull/5653/merge
git checkout --progress --force refs/remotes/pull/5653/merge
git log --no-merges --pretty=fuller -2
commit 24801655e6c74cb8e5ea457b403e35b9af843afa
Author:     Naresh Bannoth <nbannoth@in.ibm.com>
AuthorDate: Mon Mar 20 14:32:14 2023 +0530
Commit:     Naresh Bannoth <nbannoth@in.ibm.com>
CommitDate: Wed Apr 19 15:45:03 2023 +0530

    Changing the script to get the exact active controller_id in nvme.py

    currently we are using the 0] string to get the controller id in list_ctrl option.
    This may not give always the active controller ID of nvme adapter among the two
    IDs it holds. So changing the nvme option to id-ctrl and finding with exact
    controller_id string.

    Signed-off-by: Naresh Bannoth <nbannoth@in.ibm.com>

commit a8e630e03cbc923cf4c0dcb84171db0d5fa67ac3
Author:     mataotao <mataotao@uniontech.com>
AuthorDate: Tue Apr 18 15:05:48 2023 +0800
Commit:     mataotao <mataotao@uniontech.com>
CommitDate: Tue Apr 18 15:05:48 2023 +0800

    Modify the CHECK_FILE_CONTAINS and CHECK_VERSION_REGEX fields of UnionTechProbe
```

**Comment by PaulYuuu** [comment] 2023-05-25 13:58
> Hi @PaulYuuu, thank you for posting this reproducer and all this information. I really appreciated it.
> 
> Yes, I am doing some tests right now and I am aware of the problem of multiple dates, unfortunately I had to do rebase of my testing commit today, because of conflicts, which created those multiple dates. Unfortunately, I didn't find a better way of how to reproduce it, then wait for new commits on master and then open PR with some older commit without sign. So now I have to wait fore new commits to be merged into master.
> 
> If you have some better reproducer, I would welcome it.

Refer to this: https://codewithhugo.com/change-the-date-of-a-git-commit, I found a simple reproducer. You can check the result: https://github.com/avocado-framework/avocado/pull/5693 and https://github.com/avocado-framework/avocado/pull/5694.
```bash
$ git log --no-merges --pretty=fuller -1
commit e7013ff8ddbff4123f861b02a954c32a977fe007 (HEAD -> commit-test, origin/commit-test)
Author:     Yihuang Yu <yihyu@redhat.com>
AuthorDate: Tue Apr 18 15:05:48 2023 +0800
Commit:     Yihuang Yu <yihyu@redhat.com>
CommitDate: Tue Apr 18 15:05:48 2023 +0800

    Test signedoff-check
```

**Closed** 2023-06-01 18:26 UTC
Labels: bug
