### ISSUE TITLE
69lts: syntax warnings and selftest failure with Python 3.8 on Fedora 32/Rawhide

### ISSUE THREAD

**Issue by mmathesius** [avocado-framework/avocado#3292] opened 2019-09-06 18:27 UTC
```
+ /usr/bin/python3 selftests/run
BUILDSTDERR: /builddir/build/BUILD/avocado-69.1/avocado/utils/cpu.py:248: SyntaxWarning: "is" with a literal. Did you mean "=="?
BUILDSTDERR:   if value is 0:
BUILDSTDERR: /builddir/build/BUILD/avocado-69.1/avocado/utils/cpu.py:250: SyntaxWarning: "is" with a literal. Did you mean "=="?
BUILDSTDERR:   if value is 1:
BUILDSTDERR: /builddir/build/BUILD/avocado-69.1/optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py:165: SyntaxWarning: "is not" with a literal. Did you mean "!="?
BUILDSTDERR:   if name is not '':
BUILDSTDERR: ............................s.........................................s...F
BUILDSTDERR: ======================================================================
BUILDSTDERR: FAIL: test_dont_detect_non_avocado (selftests.unit.test_loader.LoaderTest)
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILD/avocado-69.1/selftests/unit/test_loader.py", line 458, in test_dont_detect_non_avocado
BUILDSTDERR:     self._check_discovery(exps, tests)
BUILDSTDERR:   File "/builddir/build/BUILD/avocado-69.1/selftests/unit/test_loader.py", line 222, in _check_discovery
BUILDSTDERR:     self.assertEqual(len(exps), len(tests), "Total count of tests not "
BUILDSTDERR: AssertionError: 2 != 0 : Total count of tests not as expected (2 != 0)
BUILDSTDERR: exps: [(<class 'avocado.core.test.PythonUnittest'>, 'dont_detect_non_avocado.StaticallyNotAvocadoTest.test'), (<class 'avocado.core.test.PythonUnittest'>, 'dont_detect_non_avocado.NotTest.test2')]
BUILDSTDERR: tests: []
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Ran 75 tests in 5.941s
BUILDSTDERR: FAILED (failures=1, skipped=2)
```

**Comment by mmathesius** [comment] 2019-09-06 19:32
Avocado 71.0 also has the syntax warning in the `varianter_yaml_to_mux` plugin.

**Comment by PraveenPenguin** [comment] 2019-09-09 05:09
@mmathesius 69 lts meant to run against Python2 this support also going to off in max 6 months , regarding Avocado 71.0  can you please provide failure stack

**Comment by mmathesius** [comment] 2019-09-09 19:09
Hi @PraveenPenguin. I'm not sure what you mean about Python 2, according to the Avocado 69.0 documentation "Avocado fully supports both Python 2 and 3" (https://avocado-framework.readthedocs.io/en/69.0/release_notes/lts/69_0.html#upgrading-installations). In any case, the above errors are appearing with Python 3.

Note: the Fedora package/module for avocado builds uses only Python 3 from F31 onwards. See https://src.fedoraproject.org/rpms/python-avocado/blob/69lts/f/python-avocado.spec#_37

And sorry about not being clear regarding Avocado 71.0, but there are no self-test failures with Fedora 32--so there is no failure stack. However, the build logs do contain the same SyntaxWarning as above--but at line 168 instead of line 165:

```
...
byte-compiling /builddir/build/BUILDROOT/python-avocado-71.0-1.fc32.x86_64/usr/lib/python3.8/site-packages/avocado_varianter_yaml_to_mux/__init__.py to __init__.cpython-38.pyc
/usr/lib/python3.8/site-packages/avocado_varianter_yaml_to_mux/__init__.py:168: SyntaxWarning: "is not" with a literal. Did you mean "!="?
writing byte-compilation script '/tmp/tmpqraq71fe.py'
/usr/bin/python3 /tmp/tmpqraq71fe.py
/usr/lib/python3.8/site-packages/avocado_varianter_yaml_to_mux/__init__.py:168: SyntaxWarning: "is not" with a literal. Did you mean "!="?
removing /tmp/tmpqraq71fe.py
...
+ /usr/lib/rpm/redhat/brp-python-bytecompile /usr/bin/python 1 0
Bytecompiling .py files below /builddir/build/BUILDROOT/python-avocado-71.0-1.fc32.x86_64/usr/lib/python3.8 using /usr/bin/python3.8
/usr/lib/python3.8/__init__.py:168: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/lib/python3.8/__init__.py:168: SyntaxWarning: "is not" with a literal. Did you mean "!="?
...
+ /usr/bin/python3 selftests/run
/builddir/build/BUILD/avocado-71.0/optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py:168: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if name is not '':
...
```

**Comment by mmathesius** [comment] 2019-09-09 19:10
> In any case, the above errors are appearing with Python 3.

More specifically, Python 3.8 as found in Fedora Rawhide (which is currently Fedora 32).

**Comment by mmathesius** [comment] 2019-09-10 16:29
I just encountered the same selftest failure (but no syntax warnings) while attempting to build 69.1LTS for Fedora 31, which is still using Python 3.7.

```
...
+ /usr/bin/python3 selftests/run
BUILDSTDERR: ............................s.........................................s...F
BUILDSTDERR: ======================================================================
BUILDSTDERR: FAIL: test_dont_detect_non_avocado (selftests.unit.test_loader.LoaderTest)
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILD/avocado-69.1/selftests/unit/test_loader.py", line 461, in test_dont_detect_non_avocado
BUILDSTDERR:     self._check_discovery(exps, tests)
BUILDSTDERR:   File "/builddir/build/BUILD/avocado-69.1/selftests/unit/test_loader.py", line 225, in _check_discovery
BUILDSTDERR:     % (len(exps), len(tests), exps, tests))
BUILDSTDERR: AssertionError: 2 != 0 : Total count of tests not as expected (2 != 0)
BUILDSTDERR: exps: [(<class 'avocado.core.test.PythonUnittest'>, 'dont_detect_non_avocado.StaticallyNotAvocadoTest.test'), (<class 'avocado.core.test.PythonUnittest'>, 'dont_detect_non_avocado.NotTest.test2')]
BUILDSTDERR: tests: []
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Ran 75 tests in 12.339s
BUILDSTDERR: FAILED (failures=1, skipped=2)
...
```

**Comment by mmathesius** [comment] 2019-09-11 20:21
PR #3303 makes it much easier to reproduce this error and warnings by simply running `make MOCK_CONFIG=fedora-31-x86_64 rpm` and `make MOCK_CONFIG=fedora-32-x86_64 rpm`.

**Comment by willianrampazzo** [comment] 2020-06-23 20:33
I could not reproduce it with the current master branch (https://github.com/avocado-framework/avocado/commit/385d7825929fd06359e36fe7611488e55e3b8ac3) and Fedora 32. Can we close this issue?

**Comment by willianrampazzo** [comment] 2020-06-23 20:36
> I could not reproduce it with the current master branch ([385d782](https://github.com/avocado-framework/avocado/commit/385d7825929fd06359e36fe7611488e55e3b8ac3)) and Fedora 32. Can we close this issue?

Forget about, I noticed it references to 69 LTS.

**Comment by willianrampazzo** [comment] 2020-06-23 21:00
The warnings with the `cpu.py` module are fixed in the current release development 81. The `avocado_varianter_yaml_to_mux` warnings were fixed on release 79. We may backport it to 69.0 if needed.

**Comment by willianrampazzo** [comment] 2021-11-17 20:00
69.0 LTS is not supported anymore. I am closing this issue. Please, open a new issue against a supported LTS if the problem still occurs.

**Closed by willianrampazzo** 2021-11-17 20:00 UTC
