### ISSUE TITLE
How to get a variable from an external file and where to place that file in ~/doc/avocado/tests folder

### ISSUE THREAD

**Issue by parimalpp** [avocado-framework/avocado#2966] opened 2018-12-12 04:23 UTC
Hi,

I am very new to avocado & know that this is a simple usecase but nowhere in the documentation i could find the exact usage of external variables or files.

I have a file /home/user/test.py for which the the file level data directory is /home/user/test.py.data/
My testscript lets say abc.py contains:

import os
from avocado import Test
class newTest(Test):
     def test_printMethod(self):   
           a= self.params.get('a',path='*',default=None)
           self.log.debug(a)

If i run #avocado run abc.py -p a=10 
a gets the value 10

Instead of using the -p parameter & passing the value of 'a' i want to place a file say abc.txt (containing a variable a=10) inside /home/user/test.py.data/ & want my test script to read the value from there using get_data()

Can you please edit my script & show how its done?
Also hopefully i can also give multiple variables inside abc.txt

**Comment by parimalpp** [comment] 2018-12-21 07:21
Can someone please reply to this query?

**Comment by clebergnu** [comment] 2019-02-22 02:11
@parimalpp there's no support for reading files from a parameter based on the test name convention *yet*.  I actually wrote a prototype some time ago, but basically the problem is that Avocado's architecture is one such that:

1) the test get's initialized with the parameters by the test runner
2) the test itself is the only entity that knows about its "data" directories (it can define new types)

Expect some major changes to the parameter system, including a solution to this situation, after the 69.0 release.  Given that a major overhaul to the parameter system is already planed:

https://trello.com/c/NTSCLnvv/962-define-and-improve-sources-of-test-params

I'm going to close this issue, because, as of now, it's not easily solvable.

**Closed by clebergnu** 2019-02-22 02:11 UTC
