### ISSUE TITLE
Sysinfo not getting collected post test guest run.

### ISSUE THREAD

**Issue by Venutiwa** [avocado-framework/avocado#2341] opened 2017-12-11 07:03 UTC
During guest run (for FIO worload) it was observed that Sysinfo that is captured post workload is not executed. The post directory created in tests results directory is empty. Looks like either sysinfo was not collected or it was not populated into post folder. However in host run of same workload we do see sysinfo captured in post directory of host test results.

Please note that there was a fix related to profilers which is part of the issue https://github.com/avocado-framework/avocado/issues/2169 which was fixed in
https://github.com/avocado-framework/avocado/pull/2254/files. This fixes, perf data collection and profilers running per test not just per job,

/home/hariharan/avocado-fvt-wrapper/results/job-2017-12-08T04.22-6208e7b/test-results/1-avocado-misc-tests_io_disk_fiotest.py_FioTest.test;ext4-fio-seq-read-679b/sysinfo# ls
post pre profile.

**Comment by ldoktor** [comment] 2017-12-13 11:05
![](https://github.trello.services/images/mini-trello-icon.png) [ISSUE: Sysinfo not getting collected post test guest run](https://trello.com/c/ew0eMTBN/1188-issue-sysinfo-not-getting-collected-post-test-guest-run)

**Comment by apahim** [comment] 2018-01-03 08:09
@Venutiwa could you please expand on "guest run"? Are you simply running Avocado in a Guest VM or are you using one of the remote plugins? Is the Guest VM configured (in avocado.conf) to `per_test = True`?

**Comment by Venutiwa** [comment] 2018-01-05 08:38
@apahim We are using avocado-vt to and virttest to run tests on guests.

**Comment by apahim** [comment] 2018-01-08 11:54
@Venutiwa, please provide the steps to reproduce the issue. Thanks!

**Comment by apahim** [comment] 2018-01-08 13:13
@Venutiwa well, if you're using some test which deploys Avocado on the Guest (i.e. https://github.com/autotest/tp-qemu/blob/master/generic/tests/avocado_guest.py), you have to make sure the configuration file which enables the sysinfo features you want is also deployed on the Guest. In that case, your test should take care of that, like copying your /etc/avocado/sysinfo/ from the Host to the Guest.

**Comment by harihare** [comment] 2018-02-23 10:10
Sorry for the delay in response. 
we are not installing avocado on the guest. we are running avocado-vt  qemu infrastructure of avocado to run the test. Hence guest will not have the avocado running to set the sysinfo. 

It will be good to know how to collect the performance data from guest for the test run in the guest using avocado-vt. 

Thanks in advance.

**Comment by ldoktor** [comment] 2018-02-23 10:38
Hello @harihare, it's quite hard to give you good advice without some background info. Ideal would be a RFC sent to mailing list with description of the situation and the expected results, ideally with some dummies and fake-results. Avocado is really flexible so we should be able to do almost anything but first we need to see the overall picture.

Here I assume you're using the https://github.com/autotest/tp-qemu/blob/master/generic/tests/avocado_guest.py test and IIUC a presense of `sysinfo` would suffice. If so we could simply add `custom_config` to that test, where one would specify the sysinfo commands and we're done.

On the other hand if you want some perf-tool integration for better reports, ideally with some cooperation between host and guest, we'd probably have to dig deeper, but it should be still doable (like a profiler which would get notified from guest over tcp/serial/...).

**Comment by ldoktor** [comment] 2018-07-12 05:29
The support to perform per-test-sysinfo-collection had been merged, it just needs to be enabled. Here the situation was about specific avocado-vt test, it's possible there as well but requires changing configuration on the destination guest, which should be implemented as part of the avocado-vt test. Let's close this issue as Avocado part seems to be implemented, feel free to follow up on avocado-vt side (unless it's already there).

**Closed by ldoktor** 2018-07-12 05:29 UTC
