### ISSUE TITLE
Writing results.tap very slow

### ISSUE THREAD

**Issue by brianjmurrell** [avocado-framework/avocado#3716] opened 2020-04-16 11:18 UTC
It would appear that it's because it's writing it one line at a time and `fsync()`ing after every write:

```
write(8, "#   01:45:02 DEBUG| [stderr] log"..., 142) = 142
fsync(8)                                = 0
write(8, "#   01:45:02 DEBUG| [stderr] ERR"..., 107) = 107
fsync(8)                                = 0
write(8, "#   01:45:02 DEBUG| [stderr] log"..., 142) = 142
fsync(8)                                = 0
write(8, "#   01:45:02 DEBUG| [stderr] ERR"..., 107) = 107
fsync(8)                                = 0
write(8, "#   01:45:02 DEBUG| [stderr] log"..., 142) = 142
fsync(8)                                = 0
write(8, "#   01:45:02 DEBUG| [stderr] ERR"..., 107) = 107
fsync(8)                                = 0
write(8, "#   01:45:02 DEBUG| [stderr] log"..., 142) = 142
fsync(8)                                = 0
write(8, "#   01:45:02 DEBUG| [stderr] ERR"..., 107) = 107
fsync(8)                                = 0
```

This is with 52.1.

**Comment by beraldoleal** [comment] 2020-04-16 12:58
@brianjmurrell what are the tests that you are running? Can you give more details about this execution?

AFAIK, we have to print every line to get a "real time" output, since that a few tests can ran for a while and we don't want to wait for all tests to finish. But I might be missing something.

**Comment by brianjmurrell** [comment] 2020-04-16 13:17
I'm not sure the nature of the tests themselves are relevant.  You could just use any simple command that produced a lot of output to reproduce.

But it's worth pointing out that the contents of this `results.tap` file seems to be quite similar to what's in `job.log` and it does not suffer the same issue.

Why do you need "real time" output in a test results file?

**Comment by beraldoleal** [comment] 2020-04-16 13:42
@brianjmurrell I'm just trying to understand how to reproduce, because I'm not able to, right now:

```bash
$ strace avocado run --tap-job-result on --tap /tmp/test.tap /bin/true /bin/true /bin/false /bin/true /bin/true /tmp/foobar 2>&1 | grep DEBUG | wc -l
0
```

All `fsync` calls that I found are not related to this DEBUG msg, that looks like is not part of TAP result.

**Comment by clebergnu** [comment] 2020-04-16 13:51
@beraldoleal is right, the synchronous I/O is really about the `results.tap` file which should be justifiable in most cases because:
 * It's supposed be pretty small I/O operations
 * We don't want to lose the results if a system crashes
 * The TAP output is internally consumed by the `replay` feature, and it allows one to "resume" a job, so it's important that we can trust (as much as possible) that a test occurred or not.

@brianjmurrell if you don't need TAP output, it should be easy to disable it. Or if you do, but don't care about these points, it should be easy to create an option for sync/async TAP output.

**Comment by beraldoleal** [comment] 2020-05-12 16:51
Closing this. Please feel free to re-open it if needed.

**Closed by beraldoleal** 2020-05-12 16:51 UTC
