### ISSUE TITLE
tearDown() not being given enough time when test times out

### ISSUE THREAD

**Issue by brianjmurrell** [avocado-framework/avocado#2908] opened 2018-11-13 14:59 UTC
Per the [discussion](https://www.redhat.com/archives/avocado-devel/2018-November/msg00017.html) on the [avocado-devel list](https://www.redhat.com/mailman/listinfo/avocado-devel), I would like to propose that `tearDown()` only getting 1 second to execute when the test times out to be a bug.

I'm not sure what a reasonable timeout for `tearDown()` after a test timeout occurs is, but I think it ought to be at least a minute.

**Comment by brianjmurrell** [comment] 2019-03-05 12:54
Any chance of this issue getting some attention?

**Comment by clebergnu** [comment] 2019-03-06 17:52
OK, making it configurable seems like a good idea.  Working on it now.

**Comment by brianjmurrell** [comment] 2019-03-11 03:32
Awesome.  Looking forward to it.

**Comment by brianjmurrell** [comment] 2019-03-19 03:39
@clebergnu 
> OK, making it configurable seems like a good idea. Working on it now.

Did you make any headway with this one?

**Comment by clebergnu** [comment] 2019-03-20 14:02
Hi @brianjmurrell , I've written a reproducer and a "dirty" PoC.  Basically, the challenge is that the runner doesn't see the individual steps (`setUp()`, `test`, and `tearDown()`) so it can't enforce individual timeouts.

So, the first step is letting the runner know about those steps.  I should have something later Today, so stay tuned!

Cheers.

**Comment by brianjmurrell** [comment] 2019-03-28 18:43
Sorry to be a nag, but just wondering how you are making out with this.

**Comment by clebergnu** [comment] 2019-03-28 18:54
Hi @brianjmurrell , I put a PoC out (https://github.com/avocado-framework/avocado/pull/3076) 8 days ago.  Could you please test it and provide feedback?

**Comment by clebergnu** [comment] 2019-06-18 12:33
@brianjmurrell I'm pushing a few PR related to this (on non PoC versions).  If you have some spare cycles and can review/ack it, it'd be appreciated.  Thanks.

**Comment by willianrampazzo** [comment] 2020-06-24 17:41
There were some improvements in the tests _timeout_ area. I'm closing this issue as there was not any activity here for some time. If this issue is still needed, feel free to reopen.

**Comment by brianjmurrell** [comment] 2020-12-02 22:41
@willianrampazzo Can you point specifically where `tearDown()` is given some extra time to do it's work please?

**Comment by willianrampazzo** [comment] 2020-12-03 13:19
> @willianrampazzo Can you point specifically where `tearDown()` is given some extra time to do it's work please?

The code added by @clebergnu (#3152) do not specifically handle the `tearDown()` method but gives some more time to the process to finish. If I recall correctly, we evaluated the possibility of adding this parameter to the `tearDown()` method, and we found some technical limitations. Of course, I may be wrong :)  If you really need a timeout parameter for the `tearDown()`, feel free to reopen this issue. We can evaluate and add the limitations, if any, to the issue for documentation.

**Comment by brianjmurrell** [comment] 2020-12-03 15:03
Does #3152 actually increase any timeouts?  It looks like it's an apples-to-apples refactor that just allows some timeouts to be configurable by the user.

But given that `tearDown()` doesn't have any timeout, I don't think that patch helps in any way.

**Comment by willianrampazzo** [comment] 2020-12-03 16:09
Reopening to better track the discussion.

**Comment by willianrampazzo** [comment] 2020-12-03 20:21
@brianjmurrell do you have a strict need to run it with the `runner` instead of the `nrunner`? I ask because there is little or no chance to add new features to the current runner with our current plan. We planned for bugfixes only in the legacy architecture on LTS 82. The plan is to deprecate the current runner in favor of the `nrunner` from now on.

**Comment by brianjmurrell** [comment] 2020-12-03 21:36
> @brianjmurrell do you have a strict need to run it with the `runner` instead of the `nrunner`?

I honestly don't know the difference.  What I can tell you is that we use 52.1 because that is what EPEL packages for EL7.  We're trying to reduce the number of third-party packages we have to package up into RPMs and DEBs and so are not overly joyed at having to use a version of Avocado that is not already patched.

> I ask because there is little or no chance to add new features to the current runner with our current plan. We planned for bugfixes only in the legacy architecture on LTS 82. The plan is to deprecate the current runner in favor of the `nrunner` from now on.

The other problem is knowing the large version delta between 52.x and 82 (or wherever such changes might land), what "gotchas" we might have waiting for us in trying to update our test infrastructure across such a big jump.

It's something we will have to do at some point, yes, but that would be a planned and resourced project.  Right now we are just looking for a Q[&D] way to give `tearDown()` some amount of time to do it's work when the test phase has used up all of the timeout.

**Comment by willianrampazzo** [comment] 2020-12-03 21:45
> I honestly don't know the difference. What I can tell you is that we use 52.1 because that is what EPEL packages for EL7. 

Oh, so it would be a feature request to LTS 52.1. That makes things even more complicated, we have the policy to do not add new features to the LTS versions. @clebergnu @beraldoleal @richtja what do you think?

**Comment by brianjmurrell** [comment] 2020-12-03 21:50
As I did with the PoC patch that @clebergnu previously provided, I would be fine with monkey-patching my installations, so having something actually land on the release branch is not strictly necessary.  If that makes things any easier.

**Comment by beraldoleal** [comment] 2020-12-03 21:53
> > I honestly don't know the difference. What I can tell you is that we use 52.1 because that is what EPEL packages for EL7.
> 
> Oh, so it would be a feature request to LTS 52.1. That makes things even more complicated, we have the policy to do not add new features to the LTS versions. @clebergnu @beraldoleal @richtja what do you think?

Yes, I think LTS patches are only hotfixes. I'm not sure it fits there.

**Comment by brianjmurrell** [comment] 2020-12-04 16:18
So, looking at @clebergnu's PoC patch in #3076 and why it doesn't work.  Is it completely expected that the value of `test_status.status.get('phase')` would be empty as it's used in:
https://github.com/clebergnu/avocado/blob/d9e5210cd6112b59f7caff98883a9748495c07dd/avocado/core/runner.py#L428

Or does that seem like it really should have worked, and there is some other issue lurking which is making `test_status.status.get('phase')` always return an empty value?

**Comment by brianjmurrell** [comment] 2020-12-14 18:16
FWIW, I was able to get this completely working.  It required 3 patches, all of which are ports of various patches landed to newer versions of Avocado.  My branch for this is https://github.com/brianjmurrell/avocado/tree/bmurrell/give-teardown-60s

I'm not going to bother with a PR for it given that it's on the unsupported 52.x LTS branch.

But just in case anyone comes here in the future looking for a solution to this, the above is it.

If any Avocado maintainer wants to look into forward porting this to a supported version, by all means, please do.

**Comment by richtja** [comment] 2024-01-09 10:32
Solved in #5795

**Closed by richtja** 2024-01-09 10:32 UTC
