### ISSUE TITLE
Error in pre_tests: 'Subscript' object has no attribute 'id'

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado#5415] opened 2022-06-28 06:55 UTC
**Describe the bug**
When running the unit tests of our plugin with most recent Avocado I get
```
Error running method "pre_tests" of plugin "fetchasset": 'Subscript' object has no attribute 'id'
```

**Steps to reproduce**
The invocation line I use for our unit tests is:
```
+ avocado run --nrunner-max-parallel-tasks=4 selftests/test_cartesian_graph.py selftests/test_cmd_parser.py selftests/test_intertest_setup.py selftests/test_params_parser.py selftests/test_state_setup.py selftests/test_vm_network.py
```

**Expected behavior**
The error above is harmless to the overall run but still should not be there.

**Current behavior**
As described above:
```
$ avocado run --nrunner-max-parallel-tasks=4 selftests/test_cartesian_graph.py selftests/test_cmd_parser.py selftests/test_intertest_setup.py selftests/test_params_parser.py selftests/test_state_setup.py selftests/test_vm_network.py
Error running method "pre_tests" of plugin "fetchasset": 'Subscript' object has no attribute 'id'
```
then the tests would run (the error is in red in the beginning).

**System information (please complete the following information):**
I highly suspect that this could be due to some API change in Avocado that is not backward compatible and thus not reflected in our Avocado I2N plugin. So any guidance on possible commits that have introduced these changes are welcome. I will then inspect and adapt out plugin if such adaptation is necessary and indeed the culprit. I am mainly reporting this as it happens with "pure" avocado run (above) but as various plugins are loaded early on this can still be third-party plugin problem cause by downstream breakage.

**Additional information**
It might also be related to the configuration of LXC spawner that I am currently testing-by-using so if you have pointers I can look into might also have to adjust the PR.

**Comment by clebergnu** [comment] 2022-07-11 18:21
@pevogam this looks a lot like what was addressed by ed9d3ddea8dc6bba68a860f24d3d5a8dc04d86b5.  Can you verify that?

**Comment by clebergnu** [comment] 2022-07-11 18:23
Another related commit is 57d3c8ecad0eba8b1958cddba99e4e4ef0d16c72 .

BTW, it doesn't look like it's caused by the LXC Spawner IMO.

**Comment by pevogam** [comment] 2022-07-12 06:13
> Another related commit is [57d3c8e](https://github.com/avocado-framework/avocado/commit/57d3c8ecad0eba8b1958cddba99e4e4ef0d16c72) .
> 
> BTW, it doesn't look like it's caused by the LXC Spawner IMO.

Indeed, very good pointers, doing this miniature diff fixes it:
```diff
diff --git a/avocado/plugins/assets.py b/avocado/plugins/assets.py
index b9b7e3cc..4571636a 100644
--- a/avocado/plugins/assets.py
+++ b/avocado/plugins/assets.py
@@ -261,6 +261,7 @@ class FetchAssetJob(JobPreTests):  # pylint: disable=R0903
         candidates = []
         for suite in job.test_suites:
             for test in suite.tests:
+                continue
                 # nrunner/resolver based test should describe their requirements
                 # explicitly using docstring statements.  But, they can still
                 # benefit from the parsing of "fetch_asset()" calls just like
```
which then brings to the question: Why was this behavior changed from https://github.com/avocado-framework/avocado/commit/ed9d3ddea8dc6bba68a860f24d3d5a8dc04d86b5 to https://github.com/avocado-framework/avocado/commit/57d3c8ecad0eba8b1958cddba99e4e4ef0d16c72? The commit message doesn't seem to explain this too much.

Quickly dumping the `test.kind` in the above code shows that all python unit tests are `avocado-instrumented` and dumping the `candidates` shows
```
('selftests/test_state_setup.py', 'StateSetupTest', 'test_qcow2_format')
('selftests/test_state_setup.py', 'StateSetupTest', 'test_qcow2_dash')
('selftests/test_state_setup.py', 'StateSetupTest', 'test_qcow2_convert')
```
so I don't quite see what in this strings tuple would cause missing `id` attribute error.

**Closed** 2023-06-08 19:02 UTC
Labels: bug
