### ISSUE TITLE
Evaluate if pre-release tests can be automatically executed on GitHub Actions

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4601] opened 2021-05-19 14:19 UTC
This is part of #3456.

Sometimes we find bugs during the pre-release tests and spend time fixing them during the code freeze. It would be good if those tests are executed regularly, like once a week, in an automated way to find bugs early.

Let's evaluate if it is possible to set a GitHub Action job that is triggered weekly and execute most, if not all, the pre-release tests.

**Comment by ana** [comment] 2021-06-21 14:33
Hi @willianrampazzo, all these tests are the ones under `selftests/pre_release `, is there any other set of tests?

**Comment by willianrampazzo** [comment] 2021-06-21 14:47
> Hi @willianrampazzo, all these tests are the ones under `selftests/pre_release `, is there any other set of tests?

It should cover all the steps, or at least most of the tests listed when executing the pre-release tests: https://avocado-framework.readthedocs.io/en/latest/guides/contributor/chapters/releasing.html#how-to-release

In a nutshell, `scripts/avocado-run-testplan -t examples/testplans/release/pre.json`.

When I was trying to come up with a release test yml for GitHub Action, I noticed we need some reorganization on that.

**Comment by ana** [comment] 2021-08-19 15:17
I'm closing this issue with PR https://github.com/avocado-framework/avocado/pull/4859
The most important tests are executed automatically now. There are some small things that can be automatized but probably the time taken to properly automate it will be too much compared to the time it'll save.

**Closed** 2021-08-19 17:59 UTC
Labels: enhancement

**Comment by ana** [comment] 2021-08-31 12:16
Even if the issue is closed, a final comment on the tasks that are still manual:
* "Check status of master branch": this can't be run automatically since it's a visual tasks.
* "Set the readthedocs.org token and check it": the token is personal to every user, so hard to run automatically.
*  "Paginator": GitHub actions don't provide a tty to test this and if you run with a job with the option `--paginator` it won't work.
