### ISSUE TITLE
Avocado crashes while trying to render the HTML report

### ISSUE THREAD

**Issue by lmr** [avocado-framework/avocado#891] opened 2015-11-24 12:39 UTC
One of our users in China has reported a problem while rendering the HTML report:

    #avocado run sleeptest
    JOB ID     : 13a596d8c3d4ea2eb5aabace094f7857386abffa
    JOB LOG    : /root/avocado/job-results/job-2015-11-24T16.31-13a596d/job.log
    TESTS      : 1
     (1/1) sleeptest.py:SleepTest.test: PASS (1.01 s)
     
    Avocado crashed: UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 65716: invalid start byte
    Traceback (most recent call last):
     
      File "/usr/lib/python2.7/site-packages/avocado-0.30.0-py2.7.egg/avocado/core/job.py", line 497, in _run
        timeout=self.timeout)
     
      File "/usr/lib/python2.7/site-packages/avocado-0.30.0-py2.7.egg/avocado/core/runner.py", line 364, in run_suite
        self.result.end_tests()
     
      File "/usr/lib/python2.7/site-packages/avocado-0.30.0-py2.7.egg/avocado/core/result.py", line 66, in end_tests
        output_plugin.end_tests()
     
      File "/usr/lib/python2.7/site-packages/avocado-0.30.0-py2.7.egg/avocado/core/plugins/htmlresult.py", line 230, in end_tests
        self._render_report()
     
      File "/usr/lib/python2.7/site-packages/avocado-0.30.0-py2.7.egg/avocado/core/plugins/htmlresult.py", line 240, in _render_report
        report_contents = renderer.render(open(template, 'r').read(), context)
     
      File "/usr/lib/python2.7/site-packages/pystache/renderer.py", line 458, in render
        return self._render_string(template, *context, **kwargs)
     
      File "/usr/lib/python2.7/site-packages/pystache/renderer.py", line 406, in _render_string
        return self._render_final(render_func, *context, **kwargs)
     
      File "/usr/lib/python2.7/site-packages/pystache/renderer.py", line 423, in _render_final
        return render_func(engine, stack)
     
      File "/usr/lib/python2.7/site-packages/pystache/renderer.py", line 404, in <lambda>
        render_func = lambda engine, stack: engine.render(template, stack)
     
      File "/usr/lib/python2.7/site-packages/pystache/renderengine.py", line 181, in render
        return parsed_template.render(self, context_stack)
     
      File "/usr/lib/python2.7/site-packages/pystache/parsed.py", line 47, in render
        parts = map(get_unicode, self._parse_tree)
     
      File "/usr/lib/python2.7/site-packages/pystache/parsed.py", line 46, in get_unicode
        return node.render(engine, context)
     
      File "/usr/lib/python2.7/site-packages/pystache/parser.py", line 218, in render
        parts.append(self.parsed.render(engine, context))
     
      File "/usr/lib/python2.7/site-packages/pystache/parsed.py", line 47, in render
        parts = map(get_unicode, self._parse_tree)
     
      File "/usr/lib/python2.7/site-packages/pystache/parsed.py", line 46, in get_unicode
        return node.render(engine, context)
     
      File "/usr/lib/python2.7/site-packages/pystache/parser.py", line 122, in render
        return engine.escape(s)
     
      File "/usr/lib/python2.7/site-packages/pystache/renderer.py", line 202, in _escape_to_unicode
        return unicode(self.escape(self._to_unicode_soft(s)))
     
      File "/usr/lib/python2.7/site-packages/pystache/renderer.py", line 186, in _to_unicode_soft
        return self.unicode(s)
     
      File "/usr/lib/python2.7/site-packages/pystache/renderer.py", line 229, in unicode
        return unicode(b, encoding, self.decode_errors)
     
    UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 65716: invalid start byte

**Comment by lmr** [comment] 2015-11-24 13:27
I've sent a patch to the user to see if it resolves the issue.

**Comment by ldoktor** [comment] 2015-11-24 14:04
Hmm, I'm wondering what character is it. I stopped having those issues a long time ago...

**Comment by lmr** [comment] 2015-11-24 14:13
@ldoktor It's a chinese user. Considering that we have a lot of people in Beijing using avocado, I wonder how we didn't hit this problem before.

**Comment by lmr** [comment] 2015-11-30 10:15
According to the user, patch doesn't work. I need to find some time to troubleshoot the problem.

**Comment by adereis** [comment] 2016-02-16 13:31
Feel free to hate me because of this, but I used to add this to my python projects:

```
# fscking braindamaged python utf-8 handling :-/
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

And plenty of people agree with me:

http://stackoverflow.com/questions/28657010/dangers-of-sys-setdefaultencodingutf-8?answertab=active#tab-top

If it will work or not in avocado, which uses plenty of third-party modules, I have no idea. But maybe users should give it a try when facing this kind of problem.

**Comment by adereis** [comment] 2016-02-16 14:24
I run tests with characters from several languages and with different LC_ALL environment variables. I couldn't crash avocado during run and html report generation, but I managed to crash it using `avocado list áéçóúwhatever` (dir must exist).

**Comment by adereis** [comment] 2016-02-16 14:26
and the workaround with 
```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```
worked flawlessly in all of my tests (including when using `avocado list` as reported above)

**Comment by ldoktor** [comment] 2016-02-16 15:05
Well we already use `utf8` for rendering the html results. The problem is it contains non-utf8 characters:

```python
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
unicode('\xff', 'utf8')
```

That's why I added extensive logs so we know where it comes from. I believe it's from json results, but I never got to the results myself...

Regarding the `avocado list`, the problem is in `astring` library:

```diff
diff --git a/avocado/utils/astring.py b/avocado/utils/astring.py
index 2c764e8..bfd46fa 100644
--- a/avocado/utils/astring.py
+++ b/avocado/utils/astring.py
@@ -1,3 +1,4 @@
+# -*- coding: utf8 -*-
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
@@ -25,6 +26,7 @@ string. Even with the dot notation, people may try to do things like
 And not notice until their code starts failing.
 """
 
+import codecs
 import os.path
 import re
 
@@ -156,7 +158,7 @@ def iter_tabular_output(matrix, header=None):
             lengths.append(len(column))
     for row in matrix:
         for i, column in enumerate(row):
-            column = unicode(column).encode("utf-8")
+            column = codecs.decode(column, "utf-8")
             col_len = len(column)
             try:
                 max_len = lengths[i]
```

This fixes it, although I'm not an encoding expert, this is something I used a while ago. I'm also usually using:

```
# -*- coding: utf8 -*-
```

but when I placed it into `scripts/avocado`, it didn't generate the proper results for the astring library. But maybe it can also help in some other cases...

**Comment by adereis** [comment] 2016-02-16 18:51
> # -*- coding: utf8 -*-

This is for the code itself (the strings you write in your text editor). It has no relationship to what happens at runtime and doesn't affect any module.

The trick with sys.setdefaultencoding('utf-8') forces utf-8 to be used everywhere inside the python process. It's considered a bad practice by many, but "it simply works(TM)". Python2 string/utf8 handling is ridiculously insane.

**Comment by ldoktor** [comment] 2016-02-17 06:26
yep, the problem is it won't fix the htmlplugin issue. So do you want me to push the `unicode(column).encode("utf-8")` vs. `codecs.decode(column, "utf-8")` modification, or do you want to bring the `defaultencoding` on our meeting?

One potential problem I see is `utf-16` which would give wrong results in avocado if you use the `defaultencoding` approach...

**Comment by ldoktor** [comment] 2016-02-17 06:46
Actually it should be `locale.getdefaultlocale()[1] or "ascii"` to use the system encoding. It worked well (you can still trick it by `LANG=C avocado list ěščě` but that is because xterm lets you write those chars. When you use `LANG=cs_CZ.ISO8859-2 xterm` and write those chars, it represents them correctly:

LANG=cs_CZ.ISO8859-2 xterm
```
avocado list ááýý -V
Type    Test
MISSING ááýý

ACCESS_DENIED: 0
BROKEN_SYMLINK: 0
EXTERNAL: 0
FILTERED: 0
INSTRUMENTED: 0
MISSING: 1
NOT_A_TEST: 0
SIMPLE: 0
VT: 0
```

LANG=cs_CZ.UTF-8 xterm
```
avocado list -V žčřý
Type    Test
MISSING žčřý

ACCESS_DENIED: 0
BROKEN_SYMLINK: 0
EXTERNAL: 0
FILTERED: 0
INSTRUMENTED: 0
MISSING: 1
NOT_A_TEST: 0
SIMPLE: 0
VT: 0
```

LANG=C xterm
```
# I was not able to write most `šěčř` chars, but those two (`áý`) were possible to pass and it still crashed avocado
avocado list -V áý
Avocado crashed unexpectedly: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)
You can find details in /var/tmp/avocado-traceback-2016-02-17_07:42:39-tpIBWa.log
```

**Comment by ldoktor** [comment] 2016-02-17 06:51
Btw when I use your trick, the result is:

```
avocado list -V ýá
Type    Test
MISSING <FD><E1>

ACCESS_DENIED: 0
BROKEN_SYMLINK: 0
EXTERNAL: 0
FILTERED: 0
INSTRUMENTED: 0
MISSING: 1
NOT_A_TEST: 0
SIMPLE: 0
VT: 0
```

And that's not what one would expect... So IMO the `codecs` solution is cleaner. No doubt it's harder as ideally you should sanitize all user inputs (args).

**Comment by clebergnu** [comment] 2016-04-25 11:49
This should be fixed by the unicode work on the referenced PR.

**Closed by clebergnu** 2016-04-25 11:49 UTC
