### ISSUE TITLE
avocado list shows SIMPLE for tests using an avocado subclass

### ISSUE THREAD

**Issue by brianjmurrell** [avocado-framework/avocado#3176] opened 2019-07-04 14:27 UTC
Using 52.1 I have written an [avocado Test subclass called I called (unimaginatively) apricot](https://github.com/daos-stack/daos/tree/master/src/tests/ftest/util/apricot).

When I use `avocado list` on any test `.py` file using the _apricot_ subclass instead of _avocadao_ class, avocado lists the test as SIMPLE instead of INSTRUMENTED:

```bash
$ avocado list --paginator off src/tests/ftest/daos_test/daos_core_test.py
SIMPLE daos_test/daos_core_test.py
```

Additionally, tag filtering doesn't seem to be working on it:

```bash
# first see what tags are in the file:
$ grep :avocado: src/tests/ftest/daos_test/daos_core_test.py
    :avocado: recursive
        :avocado: tags=all,regression,vm,unittest,medium,daos_test
$ avocado list --paginator off --filter-by-tags=regression,vm src/tests/ftest/daos_test/daos_core_test.py
# returns nothing
```

Maybe this is a bug, but it could also be that I am overlooking something, but I wouldn't know what.

**Comment by clebergnu** [comment] 2019-07-04 15:33
I'm unable to reproduce the detection as `SIMPLE` tests:

```
$ avocado --version
Avocado 52.1

$ git log HEAD~1..
commit a0fbdf010d35225ab11c4eaa7ca5b5daa8d1a673 (HEAD -> master, origin/master, origin/HEAD)
Author: David Quigley <david.quigley@intel.com>
Date:   Thu Jul 4 07:45:52 2019 -0600

    DAOS-2372 Security: Add server Certificate loading in daos_server for gRPC and provide --insecure flag (#715)
    
    The gRPC server in daos_server can use a TLS channel to protect its
    communications. This loads up the certificates needed to verify the client
    identity and encrypt the transport channel. It also provides an insecure flag
    to tell the sever not to attempt any authentication or encryption.
    
    Signed-off-by: David Quigley <david.quigley@intel.com>

$ avocado list --paginator=off src/tests/ftest/daos_test/daos_core_test.py
INSTRUMENTED src/tests/ftest/daos_test/daos_core_test.py:DaosCoreTest.test_subtest
```

And on my system it correctly sees the tags:

```
$ avocado list --paginator=off -V src/tests/ftest/daos_test/daos_core_test.py
Type         Test                                                                  Tag(s)
INSTRUMENTED src/tests/ftest/daos_test/daos_core_test.py:DaosCoreTest.test_subtest pr,unittest,medium,hw,daos_test

TEST TYPES SUMMARY
==================
ACCESS_DENIED: 0
BROKEN_SYMLINK: 0
EXTERNAL: 0
INSTRUMENTED: 1
MISSING: 0
NOT_A_TEST: 0
SIMPLE: 0

TEST TAGS SUMMARY
=================
daos_test: 1
hw: 1
medium: 1
pr: 1
unittest: 1
```

Can you please share more information about your system? Python version, Distro, etc?

**Comment by brianjmurrell** [comment] 2019-07-04 15:47
I see this on both my Fedora 30 system with:

```
$ python --version
Python 2.7.16
$ rpm -qa | grep avocado
python2-avocado-plugins-output-html-52.1-8.module_f30+2883+7f6a800a.noarch
python2-avocado-52.1-8.module_f30+2883+7f6a800a.noarch
python2-avocado-plugins-varianter-yaml-to-mux-52.1-8.module_f30+2883+7f6a800a.noarch
```

and EL7 system with:

```
$ python --version
Python 2.7.5
$ rpm -qa | grep avocado
python2-avocado-plugins-output-html-52.1-6.el7.noarch
python2-avocado-52.1-6.el7.noarch
python2-avocado-plugins-varianter-yaml-to-mux-52.1-6.el7.noarch
```

**Comment by clebergnu** [comment] 2019-07-04 16:52
@brianjmurrell I can now reproduce it in F30 with the Fedora packages... The difference is either environmental or the packages are being built with different content.  I'll keep you posted.

**Comment by brianjmurrell** [comment] 2019-07-04 17:10
Cheers!  Looking forward to hearing about what the issue is.

**Comment by clebergnu** [comment] 2019-07-04 19:51
@brianjmurrell I believe it was an environment issue.  In the first attempt (using avocado 52.1 from sources) I actually ran  `python2 src/tests/ftest/utils/apricot/setup.py develop --user` prior to attempting to run `avocado list`.  On the RPM installation (on a fresh container) I didn't.

So, I've traced the issue down to the libraries being available to Python.  When you use `:avocado: recursive`, Avocado must follow the base classes, in this case `apricot.TestWithServers` to see if or any other class up in the hierarchy inherits from `avocado.Test`.  So, the module (`apricot` in this case) must be available to be imported.  For instance, this is a "reproducer" script:

```python
import argparse
from avocado.core.loader import loader

args = argparse.Namespace()
loader.load_plugins(args)
suite = loader.discover(['/tmp/daos/src/tests/ftest/daos_test/daos_core_test.py'])
print(suite)
```

Running with `apricot` on the `PYTHONPATH` on the gives me:

```
$ PYTHONPATH=/tmp/daos/src/tests/ftest/util/apricot python2 /tmp/reproducer.py 
[('DaosCoreTest', {'tags': set(['pr', 'unittest', 'medium', 'hw', 'daos_test']), 'methodName': 'test_subtest', 'name': '/tmp/daos/src/tests/ftest/daos_test/daos_core_test.py:DaosCoreTest.test_subtest', 'modulePath': '/tmp/daos/src/tests/ftest/daos_test/daos_core_test.py'})]
```

While without it:

```
$ python2 /tmp/reproducer.py  
[(<class 'avocado.core.test.SimpleTest'>, {'name': '/tmp/daos/src/tests/ftest/daos_test/daos_core_test.py'})]
```

And the reason is that the script is marked as executable.  I recommend you clear the executable permissions, to avoid that confusion and because in it's current state it can not really be run as one.

```
$ chmod -x /tmp/daos/src/tests/ftest/daos_test/daos_core_test.py
$ python2 /tmp/reproducer.py
Traceback (most recent call last):
  File "/tmp/reproducer.py", line 6, in <module>
    suite = loader.discover(['/tmp/daos/src/tests/ftest/daos_test/daos_core_test.py'])
  File "/usr/lib/python2.7/site-packages/avocado/core/loader.py", line 294, in discover
    self._initialized_plugins)
avocado.core.loader.LoaderUnhandledReferenceError: Unable to resolve reference(s) '/tmp/daos/src/tests/ftest/daos_test/daos_core_test.py' with plugins(s) 'file', 'external', try running 'avocado list -V /tmp/daos/src/tests/ftest/daos_test/daos_core_test.py' to see the details.
```

If you don't want to make that module `apricot` available to Python, you can opt to "force" a test to be seen as an Avocado test by using `:avocado: enable` instead.  Let me know if that helps.

**Comment by brianjmurrell** [comment] 2019-07-04 20:16
Oh damnit.  How embarassing.  You are reminding me that we do wrap avocado in a script that actually `cd`s to `src/test/ftest/` and then sets `PYTHONPATH` before calling `avocado ...`.

So what actually led me down this path was trying to figure out a way to [subclass a test class](https://github.com/daos-stack/daos/blob/6f262c2a1c5e63041b0dc7189e190487e9c5c010/src/tests/ftest/daos_test/daos_core_test-rebuild.py#L27-L31) but not inherit it's  [test_subtest()](https://github.com/daos-stack/daos/blob/6f262c2a1c5e63041b0dc7189e190487e9c5c010/src/tests/ftest/daos_test/daos_core_test-rebuild.py#L27-L31) because I don't want `test_subtest()` to be discovered or run in the new [DaosCoreTestRebuild class](https://github.com/daos-stack/daos/blob/6f262c2a1c5e63041b0dc7189e190487e9c5c010/src/tests/ftest/daos_test/daos_core_test-rebuild.py#L27-L31).

Any ideas?

**Comment by clebergnu** [comment] 2019-07-04 20:49
The *right* way would be to put the base functionality into a base class, and the the classes with the test methods on others.  One alternative would be to:

```python
class DaosCoreTestRebuild(DaosCoreTest):

    """
    :avocado: enable
    """

    def test_rebuild(self):
        pass

```

This way this class will be seen as a test class, but the (safe)loader won't attempt to find other methods by recursively looking on parent classes.

**Comment by clebergnu** [comment] 2019-07-04 21:42
I'm guessing the main issue is solved, so I'm closing this issue.  Feel free to reopen or report additional issues.  Cheers.

**Closed by clebergnu** 2019-07-04 21:42 UTC
