### ISSUE TITLE
How to debug the testcase step by step?

### ISSUE THREAD

**Issue by linfenghuaster** [avocado-framework/avocado#1450] opened 2016-09-07 15:42 UTC
Python support the way, 
```python

import pdb
pdb.set_trace()

```
but the avocado does not？

**Comment by ldoktor** [comment] 2016-09-08 09:29
Hello @linfenghuaster, the problem is that tests executed under avocado have no STDIN, therefor `pdb` exits. This is to avoid hanging tests waiting for user input. This behavior is expected and there is no (sane) way to avoid it.

On the other hand debugging via STDIN is not the only way. You can use either `remote_pdb` or `pydevd`. I never tried the `remote_pdb`, but I'm a big fan of `pydevd` (Eclipse + pydev). I wrote a (slightly outdated) guide here: http://avocado-framework.readthedocs.io/en/latest/DevelopmentTips.html#remote-debug-with-eclipse The only outdated information is that `pydevd` is now available in `pip` so you don't need to add it to your python path, if you install it first.

Anyway the only dangerous thing is to set the breakpoint before or during the `Test.__init__` as avocado waits only 10s for the early status. Setting a breakpoint in `setUp`, `test*` or `tearDown` is fine, though.

I'm closing this issue as I believe it covers it but feel free to reopen it with further questions if needed.

**Closed by ldoktor** 2016-09-08 09:29 UTC

**Comment by linfenghuaster** [comment] 2016-09-09 13:47
Hello @ldoktor,  Thank you. I'm a big fan of pycharm, haha. 

1. I use this method to avoid this problem,  works fine for now, but I have not find the recommended way of avocado, so raise the issue :
```python
import sys
import pdb


class MyPdb(pdb.Pdb):

    def interaction(self, frame, traceback):
        stdin_ = sys.stdin

        try:
            sys.stdin = file('/dev/stdin')
            pdb.Pdb.interaction(self, frame, traceback)
        finally:
            sys.stdin = stdin_


def set_trace(frame=None):
    MyPdb().set_trace(frame)

```

By the way,   the 10s seems to a little short, avocado itself occupies 2-3s,  if many modules are imported,
for example multiprocessing(about 0.5s), it is easy to reach the limit.

**Comment by ldoktor** [comment] 2016-09-09 17:13
Well, nobody complained about the limit so far, feel free to suggest different one with an example where it fails. Even `avocado-vt` tests are quite quick to load...

Nice way to avoid `stdin`, it'd be nice to send a section describing how you use `pycharm` to debug avocado, if you have time...

**Comment by linfenghuaster** [comment] 2016-09-11 03:25
The code is debugged on the linux platform, the pycharm is just used as a python editor on the windows platform, and the modified code is mounted to the linux's host with mount.cifs protocol. So the loding of modules  will spend a little more time because through network.

**Comment by ldoktor** [comment] 2016-09-12 08:58
Interesting. Well you can manually change the `early_status` wait in `avocado/core/runner.py` around line 51:

```python
test_status.wait_for_early_status(proc, 10)
```
to a greater value (I use 99999), or simply set the breakpoint after the `__init__`.

As for the debugging, I see you found a workaround which works for you, which is great and I hope it'll keep working fine.
