### ISSUE TITLE
tearDown does not run when a test times out

### ISSUE THREAD

**Issue by dgibson** [avocado-framework/avocado#5707] opened 2023-06-22 01:01 UTC
**Describe the bug**
When a test is interrupted because it reaches the `timeout` set in the class, rather than because of an internal exception, the `tearDown()` functions are not called, which may leave debris on the system.

**Steps to reproduce**

Create `failtocleanup.py` as follows:

```
#! /usr/bin/python3

import os
import os.path
import time

import avocado


class FailToCleanup(avocado.Test):
    FILE = '/tmp/test1'
    timeout = 15.0

    def setUp(self):
        assert not os.path.exists(self.FILE)
        open(self.FILE, 'w').write("hello")

    def tearDown(self):
        os.remove(self.FILE)

    def test(self):
        time.sleep(20.0)
        assert os.path.exists(self.FILE)
```

Run, `avocado run failtocleanup.py`.

**Expected behavior**

`tearDown()` runs, so `/tmp/test1` is removed after the test completes.

**Current behavior**

`/tmp/test1` is left over after the test is timed out.

**System information (please complete the following information):**
 - OS: Fedora 38
 - Avocado version: `Avocado 101.0`
 - Avocado installation method: tested with both avocado 101.1 installed with venv+pip, and packaged (rpm) avocado 92.0 in Fedora.

**Comment by richtja** [comment] 2023-06-22 11:05
Hi @dgibson thank you for reporting this. It is a known issue and it is connected to #4994. I won't close this since it has additional information and nice reproducer which will be useful for solving #4994

**Closed** 2023-11-10 13:53 UTC
Labels: bug, customer:Passt
