### ISSUE TITLE
assets fetch command is not downloading assets

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4812] opened 2021-07-30 15:11 UTC
```
$ avocado --show=all assets fetch  examples/tests/assets.py
Fetching assets from examples/tests/assets.py.
```
But the asset is not downloaded. 

During a quick investigation, IIUC, `avocado assets fetch` commands uses `ast` for parsing methods inside Avocado instrumented tests. Due to the nature of ast `ast.Call.args` *can be an empty list*, according to the documentation:

> When creating a Call node, args and keywords are required, but they can be empty lists. starargs and kwargs are optional.

And I think that is exactly what I'm getting when trying to run a basic example above.

I could confirm that ast.parse is not filling the args:

```python
>> p = ast.parse("self.fetch_asset(name=hello,
                                   locations=hello_locations,
                                   asset_hash='cb0470b0e8f4f7768338f5c5cfe1688c90fbbc74')")
>> p.body[0].value.args
[]
>> p.body[0].value
 <_ast.Call at 0x7f1638b289d0>
```

Maybe I'm missing something?

Please, anyone could point me to a working example?

**Comment by willianrampazzo** [comment] 2021-08-02 15:22
The key lines here are:

https://github.com/avocado-framework/avocado/blob/ba7068fddaa3b4abf947a87741b55e01ce30ba0f/avocado/plugins/assets.py#L92-L94

I thought I had documented that, but I could not find it. I'll update the documentation explaining the restricted cases `assets fetch` command-line supports right now.

So, https://github.com/avocado-framework/avocado/blob/master/examples/tests/assets.py is an example of how to fetch assets for a test, but not an example for the `assets fetch` command-line, as https://github.com/avocado-framework/avocado/blob/ba7068fddaa3b4abf947a87741b55e01ce30ba0f/examples/tests/assets.py#L15 is not a supported case.

**Comment by beraldoleal** [comment] 2021-08-02 16:39
@willianrampazzo thank you for the explanation. Yes, we need to document this better since `avocado assets fetch` needs an `AVOCADO_INSTRUMENTED` test as argument.

**Comment by beraldoleal** [comment] 2021-08-02 16:49
What are the supported cases?

```python
p = ast.parse("self.fetch_asset(name='foo', locations=['https://paste.centos.org/view/ac45d38d'], asset_hash='cb0470b0e8f4f7768338f5c5cfe1688c90fbbc74')")
```

Gives me the same result.

**Comment by beraldoleal** [comment] 2021-08-02 17:06
@willianrampazzo the problem is that ast will parse any named argument into the `keywords` key, instead of `args` key. Currently our code is using `args`. If we have plans to keep supporting this, IIUC, we need to improve the parser to be able to get from `keywords` as well.

**Comment by willianrampazzo** [comment] 2021-08-02 17:23
> @willianrampazzo the problem is that ast will parse any named argument into the `keywords` key, instead of `args` key. Currently our code is using `args`. If we have plans to keep supporting this, IIUC, we need to improve the parser to be able to get from `keywords` as well.

Yep, that's it.

**Comment by willianrampazzo** [comment] 2021-08-02 17:31
So, is it fine to update the documentation? Or should we extend the support of this command?

**Comment by willianrampazzo** [comment] 2021-08-02 17:59
Okay, this part of the code was supposed to handle kwargs:

https://github.com/avocado-framework/avocado/blob/ba7068fddaa3b4abf947a87741b55e01ce30ba0f/avocado/plugins/assets.py#L103-L120

I'm moving this issue back to bug and will take a look at it.

**Comment by clebergnu** [comment] 2021-08-02 18:11
@willianrampazzo @beraldoleal I think I hacked up a quick (and dirty?) solution to this issue.  But I believe we should still document the supported cases briefly (which I haven't done).

**Comment by willianrampazzo** [comment] 2021-08-02 18:24
so, after creating a new branch to work on the keyword problem reported by @beraldoleal, I cannot reproduce that problem anymore using:

```
diff --git a/examples/tests/assets.py b/examples/tests/assets.py
index 89413bb1..399c4655 100644
--- a/examples/tests/assets.py
+++ b/examples/tests/assets.py
@@ -12,9 +12,9 @@ class Hello(Test):
                    'http://gnu.c3sl.ufpr.br/ftp/',
                    'ftp://ftp.funet.fi/pub/gnu/prep/hello/']
         hello = 'hello-2.9.tar.gz'
-        hello_locations = ["%s%s" % (loc, hello) for loc in mirrors]
+        hello_locations = 'https://mirrors.kernel.org/gnu/hello/hello-2.9.tar.gz'
         hello_sig = 'hello-2.9.tar.gz.sig'
-        hello_sig_locations = ["%s%s" % (loc, hello_sig) for loc in mirrors]
+        hello_sig_locations = 'https://mirrors.kernel.org/gnu/hello/hello-2.9.tar.gz.sig'
         self.hello = self.fetch_asset(
             name=hello,
             locations=hello_locations,
```

This works as expected:

```
[wrampazz@wrampazz avocado.dev]$ ls ~/avocado/data/cache/by_name/hello-2.9.tar.gz*
ls: cannot access '/home/wrampazz/avocado/data/cache/by_name/hello-2.9.tar.gz*': No such file or directory

[wrampazz@wrampazz avocado.dev]$ avocado assets fetch examples/tests/assets.py
Fetching assets from examples/tests/assets.py.
DEBUG:root:Retrieved URL "https://mirrors.kernel.org/gnu/hello/hello-2.9.tar.gz": content-length 723645, date: "Mon, 02 Aug 2021 18:18:24 GMT", last-modified: "Wed, 09 Oct 2013 23:49:30 GMT"
DEBUG:root:Retrieved URL "https://mirrors.kernel.org/gnu/hello/hello-2.9.tar.gz.sig": content-length 190, date: "Mon, 02 Aug 2021 18:18:27 GMT", last-modified: "Wed, 09 Oct 2013 23:49:31 GMT"
  File hello-2.9.tar.gz fetched or already on cache.
  File hello-2.9.tar.gz.sig fetched or already on cache.

[wrampazz@wrampazz avocado.dev]$ ls ~/avocado/data/cache/by_name/hello-2.9.tar.gz*
/home/wrampazz/avocado/data/cache/by_name/hello-2.9.tar.gz
/home/wrampazz/avocado/data/cache/by_name/hello-2.9.tar.gz-CHECKSUM
/home/wrampazz/avocado/data/cache/by_name/hello-2.9.tar.gz.sig
/home/wrampazz/avocado/data/cache/by_name/hello-2.9.tar.gz.sig-CHECKSUM
```

**Comment by willianrampazzo** [comment] 2021-08-02 18:25
> @willianrampazzo @beraldoleal I think I hacked up a quick (and dirty?) solution to this issue. But I believe we should still document the supported cases briefly (which I haven't done).

Thanks, I'll review it and work on the documentation.

**Comment by willianrampazzo** [comment] 2021-08-02 18:37
Reopening to add missing documentation.

**Comment by willianrampazzo** [comment] 2021-08-03 17:18
Closing as #4821 got merged.

**Closed by willianrampazzo** 2021-08-03 17:18 UTC
Labels: bug, documentation
