### ISSUE TITLE
race conditions in selftests trigger random build failures

### ISSUE THREAD

**Issue by mmathesius** [avocado-framework/avocado#1619] opened 2016-11-15 19:38 UTC
Now that selftests have been enabled during package build checks, the build will occasionally fail in test_interrupt.py:
```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.pTKR4Y
+ umask 022
+ cd /builddir/build/BUILD
+ cd avocado-43.0
+ selftests/run
.s.s.s.s.s..................................................................................................................................................s..........s.s.s.s.s.s........................................................................................................................F.
======================================================================
FAIL: test_badly_behaved (selftests.functional.test_interrupt.InterruptTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/avocado-43.0/selftests/functional/test_interrupt.py", line 121, in test_badly_behaved
    self.assertIn('Killing test subprocess', proc.get_output())
AssertionError: 'Killing test subprocess' not found in 'JOB ID     : 661ee16287d1e2281ed0811397b22dbc54193683\nJOB LOG    : /tmp/avocado_selftests.functional.test_interruptXYb3gK/job-2016-11-15T18.47-661ee16/job.log\nTESTS      : 3\n (1/3) /tmp/avocado_interrupt_testeu1fcg/wontquit-ebVBV:  \nInterrupt requested. Waiting 2 seconds for test to finish (ignoring new Ctrl+C until then)\n\nINTERRUPTED (1.19 s)\nRESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 2 | WARN 0 | INTERRUPT 1\nTESTS TIME : 1.19 s\n'
----------------------------------------------------------------------
Ran 287 tests in 134.763s
FAILED (failures=1, skipped=12)
error: Bad exit status from /var/tmp/rpm-tmp.pTKR4Y (%check)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.pTKR4Y (%check)
```

**Comment by mmathesius** [comment] 2016-11-16 19:59
Another random selftest failure encountered when running a package build. This appears to be a race condition when building on a heavily loaded machine where it takes longer than 2 seconds for the script to initialize the test framework and execute os.abort()...

```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.rCKeEr
+ umask 022
+ cd /builddir/build/BUILD
+ cd avocado-43.0
+ selftests/run
............................s........................................s.s.s.s.s.s.......................s.s.s.s.s.................................................................................................................................s...s...........................s.s................................................................F.
======================================================================
FAIL: test_runner_abort (selftests.functional.test_basic.RunnerOperationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/avocado-43.0/selftests/functional/test_basic.py", line 365, in test_runner_abort
    "Avocado did not return rc %d:\n%s" % (expected_rc, result))
AssertionError: Avocado did not return rc 1:
Command: ./scripts/avocado run --sysinfo=off --job-results-dir /tmp/avocado_selftests.functional.test_basicDsn_KF --xunit - abort.py
Exit status: 8
Duration: 4.16302490234
Stdout:
<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="avocado" skipped="0" tests="1" time="3.84860301018" timestamp="2016-11-15 20:04:50.655679">
	<testcase classname="AbortTest" name="1-abort.py:AbortTest.test" time="3.84860301018">
		<error message="Test died without reporting the status.
Runner error occurred: Timeout reached
Original status: ERROR
{'traceback': 'Traceback not available', 'class_name': 'AbortTest', 'debugdir': None, 'time_end': -1, 'paused': False, 'time_start': -1, 'early_status': True, 'basedir': None, 'resultsdir': None, 'time_elapsed': 3.8486030101776123, 'params': &lt;AvocadoParams *: * (['//']),0: /run/* ([])&gt;, 'logdir': '/tmp/avocado_selftests.functional.test_basicDsn_KF/job-2016-11-15T20.04-de88697/test-results/1-abort.py:AbortTest.test', 'job_unique_id': 'de88697a84f7f7d6687950ceab6d8fe3ea9604d4', 'srcdir': None, 'job_logdir': '/tmp/avocado_selftests.functional.test_basicDsn_KF/job-2016-11-15T20.04-de88697', 'status': 'ERROR', 'workdir': None, 'depsdir': None, 'text_output': '', 'running': False, 'sysinfodir': None, 'logfile': '/tmp/avocado_selftests.functional.test_basicDsn_KF/job-2016-11-15T20.04-de88697/test-results/1-abort.py:AbortTest.test/debug.log', 'fail_reason': 'Test died without reporting the status.', 'name': '1-abort.py:AbortTest.test', 'whiteboard': '', 'fail_class': 'type', 'timeout': 2.0, 'paused_msg': ''}" type="type
RUNNER">
<![CDATA[Traceback not available]]>			<system-out>
<![CDATA[Runner error occurred: Timeout reached
Original status: ERROR
{'traceback': 'Traceback not available', 'class_name': 'AbortTest', 'debugdir': None, 'time_end': -1, 'paused': False, 'time_start': -1, 'early_status': True, 'basedir': None, 'resultsdir': None, 'time_elapsed': 3.8486030101776123, 'params': <AvocadoParams *: * (['//']),0: /run/* ([])>, 'logdir': '/tmp/avocado_selftests.functional.test_basicDsn_KF/job-2016-11-15T20.04-de88697/test-results/1-abort.py:AbortTest.test', 'job_unique_id': 'de88697a84f7f7d6687950ceab6d8fe3ea9604d4', 'srcdir': None, 'job_logdir': '/tmp/avocado_selftests.functional.test_basicDsn_KF/job-2016-11-15T20.04-de88697', 'status': 'ERROR', 'workdir': None, 'depsdir': None, 'text_output': '', 'running': False, 'sysinfodir': None, 'logfile': '/tmp/avocado_selftests.functional.test_basicDsn_KF/job-2016-11-15T20.04-de88697/test-results/1-abort.py:AbortTest.test/debug.log', 'fail_reason': 'Test died without reporting the status.', 'name': '1-abort.py:AbortTest.test', 'whiteboard': '', 'fail_class': 'type', 'timeout': 2.0, 'paused_msg': ''}
]]>			</system-out>
		</error>
	</testcase>
</testsuite>
Stderr:
PID:
31301
----------------------------------------------------------------------
Ran 325 tests in 80.031s
FAILED (failures=1, skipped=16)
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.rCKeEr (%check)
    Bad exit status from /var/tmp/rpm-tmp.rCKeEr (%check)
```

**Comment by mmathesius** [comment] 2016-11-16 20:36
My original selftest failure report is also likely a race condition. After scanning through other selftest scripts that call time.sleep(), it appears there may be other race conditions--particularly if the checks are run on heavily loaded machines where things don't always react as quickly as expected. (I'll change the title of this issue according.)

**Comment by ldoktor** [comment] 2016-11-18 12:18
Well this is actually expected. We could try being more lenient and increase the timeouts, but for example 10s timeout for test initialization seems enough... Let me create a card to look at those tests and increase the timeouts. It's easy to reproduce it with `stress -c 10 -m 4 -t 30 -i 10 -d 10` running in the background.

**Comment by ldoktor** [comment] 2016-11-18 12:21
![](https://github.trello.services/images/mini-trello-icon.png) [Increase selftest timeouts (and related code)](https://trello.com/c/kftTQkwE/872-increase-selftest-timeouts-and-related-code)

**Comment by clebergnu** [comment] 2016-12-07 03:16
@mmathesius I'm closing this one since we've worked on two different approaches to eliminate those failures.

If you do hit this on Avocado >= 44.0, please let us know.

**Closed by clebergnu** 2016-12-07 03:16 UTC

**Comment by mmathesius** [comment] 2016-12-07 13:34
Great. Thank you. I will.
