### ISSUE TITLE
avocado 63.0 package fails to build in Fedora Rawhide due to selftest issues

### ISSUE THREAD

**Issue by mmathesius** [avocado-framework/avocado#2721] opened 2018-07-18 19:02 UTC
Attempts to build avocado 63.0 in Rawhide fail during selftests.

I fixed a few of the issues I ran into with a PR I just created, https://github.com/avocado-framework/avocado/pull/2720. That PR also includes an update to provide diagnostic information for an assertion in `test_dry_run()` that is failing for reasons I do not understand.

When including the above mentioned PR and attempting to build the package locally using `mock`, the build fails at:
```
+ LANG=en_US.UTF-8                                                                                                                                                           
+ AVOCADO_CHECK_LEVEL=0                                                                                                                                                      
~/build/BUILD/avocado-63.0                                                                                                                                                   
+ UNITTEST_AVOCADO_CMD=/builddir/.local/bin/avocado                                                                                                                          
+ /usr/bin/python3 selftests/run                                                                                                                                             
Command 'sudo' could not be found in any of the PATH dirs: ['/usr/sbin', '/sbin', '/usr/local/bin', '/usr/libexec', '/usr/local/sbin', '/bin', '/builddir/.local/bin', '/buil
ddir/bin', '/usr/libexec/python2-sphinx', '/usr/bin']                                                                                                                        
Parameter sudo=True provided, but sudo was not found. Please consider adding sudo to your OS image                                                                           
......................s.........................................s......................Failed to enable paginator: Unable to enable pagination: Command 'just' could not be f
ound in any of the PATH dirs: ['mocking']                                                                                                                                    
................................................................................................................ssssss...........sssss...................s...................
........................................................F                                                                                                                    
======================================================================                                                                                                       
FAIL: test_dry_run (selftests.functional.test_basic.RunnerOperationTest)                                                                                                     
----------------------------------------------------------------------                                                                                                       
Traceback (most recent call last):                                                                                                                                           
  File "/builddir/build/BUILD/avocado-63.0/selftests/functional/test_basic.py", line 532, in test_dry_run                                                                    
    "Avocado log count for param '%s' not as expected:\n%s" % (line, log))                                                                                                   
AssertionError: 0 != 4 : Avocado log count for param '/:foo ==> 1' not as expected:                                                                                          
...
```

When I submitted the same package build to `koji` (see https://koji.fedoraproject.org/koji/taskinfo?taskID=28415598), the build fails at:
```
~/build/BUILD/avocado-63.0
+ popd
+ LANG=en_US.UTF-8
+ AVOCADO_CHECK_LEVEL=0
+ UNITTEST_AVOCADO_CMD=/builddir/.local/bin/avocado
+ /usr/bin/python2 selftests/run
No handlers could be found for logger "avocado.test"
...................................................s.................ssssss.....sssss......................................................................................................................................................................................................ss........s..ss......ss.........s................s..................................s....s....ss...............s.ss..F
======================================================================
FAIL: test_simplewarning (selftests.functional.test_basic.RunnerSimpleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/avocado-63.0/selftests/functional/test_basic.py", line 744, in test_simplewarning
    (expected_rc, result))
AssertionError: Avocado did not return rc 0:
...
```

**Comment by clebergnu** [comment] 2018-07-18 19:08
Hi @mmathesius pr #2720 looks good, just needs a `Signed-off-by` line.  WRT rawhide, yes, I found similar issues and took note here:

https://trello.com/c/544JmwRv/1375-rpm-build-failures-on-f29

Given that your PR already fixes some of that, I'm moving that card to WIP.  I'll take a look at the other issues preventing it from building.

**Comment by mmathesius** [comment] 2018-07-18 20:48
@clebergnu I was not aware of that make recipe. Thanks! I was just manually running `git archive` from my local repo, then using `fedpkg` to create the SRPM, and `mock` to build it locally. In this case, I _also_ used `fedpkg` to throw the SRPM to `koji` for a scratch build--since that seems to turn up additional strange and unusual failures.

**Comment by clebergnu** [comment] 2018-07-18 21:39
One of the errors I'm getting is rawhide is on `test_dry_run (selftests.functional.test_basic.RunnerOperationTest)`

Which can be seen here:

```
2018-07-18 16:27:07,022 test             L0594 INFO | START 1-passtest.py:PassTest.test
2018-07-18 16:27:07,022 test             L0298 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2018-07-18 16:27:07,023 test             L1328 INFO | Test params:
2018-07-18 16:27:07,023 stacktrace       L0041 ERROR| 
2018-07-18 16:27:07,023 stacktrace       L0044 ERROR| Reproduced traceback from: /builddir/build/BUILD/avocado-f09e14ce1b00295a254b6d4d109f1438d6beec80/avocado/core/test.py:818
2018-07-18 16:27:07,024 stacktrace       L0047 ERROR| Traceback (most recent call last):
2018-07-18 16:27:07,024 stacktrace       L0047 ERROR|   File "/builddir/build/BUILD/avocado-f09e14ce1b00295a254b6d4d109f1438d6beec80/avocado/core/test.py", line 1331, in setUp
2018-07-18 16:27:07,024 stacktrace       L0047 ERROR|     self.cancel('Test cancelled due to --dry-run')
2018-07-18 16:27:07,024 stacktrace       L0047 ERROR|   File "/builddir/build/BUILD/avocado-f09e14ce1b00295a254b6d4d109f1438d6beec80/avocado/core/test.py", line 1043, in cancel
2018-07-18 16:27:07,024 stacktrace       L0047 ERROR|     raise exceptions.TestCancel(message)
2018-07-18 16:27:07,024 stacktrace       L0047 ERROR| avocado.core.exceptions.TestCancel: Test cancelled due to --dry-run
2018-07-18 16:27:07,024 stacktrace       L0048 ERROR| 
2018-07-18 16:27:07,024 test             L0998 ERROR| CANCEL 1-passtest.py:PassTest.test -> TestCancel: Test cancelled due to --dry-run
```

The ```Test params:``` line should be followed by the params, but it's not.

**Comment by clebergnu** [comment] 2018-07-18 23:52
OK, I can reproduce it under rawhide.  It only manifests when running under Python 3:

```
avocado run --sysinfo=off passtest.py failtest.py gendata.py --json - --mux-inject foo:1 bar:2 baz:3 foo:foo:a foo:bar:b foo:baz:c bar:bar:bar --dry-run                                          
Error running method "initialize" of plugin "yaml_to_mux": generator raised StopIteration
Error running method "update_defaults" of plugin "yaml_to_mux": generator raised StopIteration
Error running method "__len__" of plugin "yaml_to_mux": 'YamlToMux' object has no attribute 'variant_ids'
{
    "cancel": 4,
    "debuglog": "/var/tmp/avocado-dry-run-gk2qzfeo/job-2018-07-18T19.50-0000000/job.log",
    "errors": 0,
    "failures": 0,
    "job_id": "0000000000000000000000000000000000000000",
    "pass": 0,
    "skip": 0,
    "tests": [
        {
            "end": 1531957848.955243,
            "fail_reason": "Test cancelled due to --dry-run",
            "id": "1-passtest.py:PassTest.test",
            "logdir": "/var/tmp/avocado-dry-run-gk2qzfeo/job-2018-07-18T19.50-0000000/test-results/1-passtest.py_PassTest.test",
            "logfile": "/var/tmp/avocado-dry-run-gk2qzfeo/job-2018-07-18T19.50-0000000/test-results/1-passtest.py_PassTest.test/debug.log",
            "start": 1531957848.951072,
            "status": "CANCEL",
            "time": 0.004171133041381836,
            "whiteboard": ""
        },
        {
            "end": 1531957849.0316677,
            "fail_reason": "Test cancelled due to --dry-run",
            "id": "2-failtest.py:FailTest.test",
            "logdir": "/var/tmp/avocado-dry-run-gk2qzfeo/job-2018-07-18T19.50-0000000/test-results/2-failtest.py_FailTest.test",
            "logfile": "/var/tmp/avocado-dry-run-gk2qzfeo/job-2018-07-18T19.50-0000000/test-results/2-failtest.py_FailTest.test/debug.log",
            "start": 1531957849.0273361,
            "status": "CANCEL",
            "time": 0.0043315887451171875,
            "whiteboard": ""
        },
        {
            "end": 1531957849.1004987,
            "fail_reason": "Test cancelled due to --dry-run",
            "id": "3-gendata.py:GenDataTest.test_bsod",
            "logdir": "/var/tmp/avocado-dry-run-gk2qzfeo/job-2018-07-18T19.50-0000000/test-results/3-gendata.py_GenDataTest.test_bsod",
            "logfile": "/var/tmp/avocado-dry-run-gk2qzfeo/job-2018-07-18T19.50-0000000/test-results/3-gendata.py_GenDataTest.test_bsod/debug.log",
            "start": 1531957849.0961304,
            "status": "CANCEL",
            "time": 0.004368305206298828,
            "whiteboard": ""
        },
        {
            "end": 1531957849.1850076,
            "fail_reason": "Test cancelled due to --dry-run",
            "id": "4-gendata.py:GenDataTest.test_json",
            "logdir": "/var/tmp/avocado-dry-run-gk2qzfeo/job-2018-07-18T19.50-0000000/test-results/4-gendata.py_GenDataTest.test_json",
            "logfile": "/var/tmp/avocado-dry-run-gk2qzfeo/job-2018-07-18T19.50-0000000/test-results/4-gendata.py_GenDataTest.test_json/debug.log",
            "start": 1531957849.1806479,
            "status": "CANCEL",
            "time": 0.004359722137451172,
            "whiteboard": ""
        }
    ],
    "time": 0.017230749130249023,
    "total": 4
}
```

The `yaml_to_mux` failures end up producing no parameters to the tests.

**Comment by ldoktor** [comment] 2018-07-19 12:55
OK, I see, I need to get back to https://trello.com/c/Q8QVmj8E/1254-bug-non-ascii-character-breaks-yaml2mux that should solve those kind of issues... Hopefully the `:recursive:` PR will go smoothly so I can fully focus on this one now.

**Comment by clebergnu** [comment] 2018-07-19 21:56
I have a simpler reproducer:

```
$ avocado variants --mux-inject 'foo:1'
Error running method "initialize" of plugin "yaml_to_mux": generator raised StopIteration
Error running method "update_defaults" of plugin "yaml_to_mux": generator raised StopIteration
Error running method "__len__" of plugin "yaml_to_mux": 'YamlToMux' object has no attribute 'variant_ids'
Variant :    /
$ python3 --version
Python 3.7.0
$ pip3 freeze | grep PyYAML
PyYAML==4.2b4
```

While this, works fine:

```
$ avocado variants --mux-inject 'foo:1'
Multiplex variants (1):
Variant -60ed:    /
$ python3 --version
Python 3.6.5
$ pip3 freeze | grep PyYAML
PyYAML==4.2b4
```

**Comment by clebergnu** [comment] 2018-07-19 23:28
Looks like https://www.python.org/dev/peps/pep-0479/ is "to blame" here.

**Comment by clebergnu** [comment] 2018-07-20 17:41
And a simpler reproducer:

```python
from avocado_varianter_yaml_to_mux.mux import MuxTree, MuxTreeNode
[_ for _ in MuxTree(root=MuxTreeNode(''))]
```

When run under Python 3.7:

```
Traceback (most recent call last):
  File "/home/cleber/src/avocado/optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py", line 74, in _iter_mux_leaves
    node = queue.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cleber/src/avocado/optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py", line 76, in _iter_mux_leaves
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/muxtree.py", line 2, in <module>
    [_ for _ in MuxTree(root=MuxTreeNode(''))]
  File "/home/cleber/src/avocado/optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py", line 58, in __init__
    for node in self._iter_mux_leaves(root):
RuntimeError: generator raised StopIteration
```

**Comment by clebergnu** [comment] 2018-07-20 18:55
@mmathesius this fixes the F29 builds for me.  Would you please try it?

**Comment by mmathesius** [comment] 2018-07-20 21:00
@clebergnu PR #2723 (along with PR #2720) _does_ fix the F29 builds for me locally using mock--so I think that change is good. I checked it by incorporating those fixes into my fork of the latest downstream Fedora package at https://src.fedoraproject.org/fork/merlinm/rpms/python-avocado/commits/latest.

Unfortunately, handing the same SRPM to koji for building in Rawhide (see https://koji.fedoraproject.org/koji/taskinfo?taskID=28476962) still blows up, but differently:

```
~/build/BUILD/avocado-63.0
+ LANG=en_US.UTF-8
+ AVOCADO_CHECK_LEVEL=0
+ UNITTEST_AVOCADO_CMD=/builddir/.local/bin/avocado
+ /usr/bin/python2 selftests/run
No handlers could be found for logger "avocado.test"
..........ssssss................................................................................................................................sssss.....................................................s..............................................................................ssss................................................sss........s..ss...............ssss..s................s.s.......................................s....s....ss...............s.ss..F
======================================================================
FAIL: test_simplewarning (selftests.functional.test_basic.RunnerSimpleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/avocado-63.0/selftests/functional/test_basic.py", line 743, in test_simplewarning
    (expected_rc, result))
AssertionError: Avocado did not return rc 0:
command: '/builddir/.local/bin/avocado run --job-results-dir /tmp/avocado_selftests.functional.test_basicURS8EB --sysinfo=off examples/tests/simplewarning.sh --show-job-log'
exit_status: 1
duration: 0.633995771408081
interrupted: False
pid: 5502
encoding: 'UTF-8'
stdout: 'found extension EntryPoint.parse(\'teststmpdir = avocado.plugins.teststmpdir:TestsTmpDir\')\nfound extension EntryPoint.parse(\'jobscripts = avocado.plugins.jobscripts:JobScripts\')\nfound extension EntryPoint.parse(\'human = avocado.plugins.human:HumanJob\')\nfound extension EntryPoint.parse(\'json_variants = avocado.plugins.json_variants:JsonVariants\')\nfound extension EntryPoint.parse(\'yaml_to_mux = avocado_varianter_yaml_to_mux:YamlToMux\')\nfound extension EntryPoint.parse(\'varianter_pict = avocado_varianter_pict:VarianterPict\')\nfound extension EntryPoint.parse(\'json_variants = avocado.plugins.json_variants:JsonVariants\')\nfound extension EntryPoint.parse(\'yaml_to_mux = avocado_varianter_yaml_to_mux:YamlToMux\')\nfound extension EntryPoint.parse(\'varianter_pict = avocado_varianter_pict:VarianterPict\')\nfound extension EntryPoint.parse(\'json_variants = avocado.plugins.json_variants:JsonVariants\')\nfound extension EntryPoint.parse(\'yaml_to_mux = avocado_varianter_yaml_to_mux:YamlToMux\')\nfound extension EntryPoint.parse(\'varianter_pict = avocado_varianter_pict:VarianterPict\')\nCommand line: /builddir/.local/bin/avocado run --job-results-dir /tmp/avocado_selftests.functional.test_basicURS8EB --sysinfo=off examples/tests/simplewarning.sh --show-job-log\n\nAvocado version: 63.0\n\nConfig files read (in order):\n/builddir/build/BUILD/avocado-63.0/avocado/etc/avocado/avocado.conf\n/builddir/build/BUILD/avocado-63.0/avocado/etc/avocado/conf.d/resultsdb.conf\n/builddir/build/BUILD/avocado-63.0/avocado/etc/avocado/conf.d/gdb.conf\n/builddir/build/BUILD/avocado-63.0/avocado/etc/avocado/conf.d/result_upload.conf\n/builddir/build/BUILD/avocado-63.0/avocado/etc/avocado/conf.d/jobscripts.conf\n/builddir/.config/avocado/avocado.conf\n\nAvocado config:\nSection.Key                              Value\ndatadir.paths.base_dir                   /var/lib/avocado\ndatadir.paths.test_dir                   /usr/share/doc/avocado/tests\ndatadir.paths.data_dir                   /var/lib/avocado/data\ndatadir.paths.logs_dir                   ~/avocado/job-results\nsysinfo.collect.enabled                  True\nsysinfo.collect.commands_timeout         -1\nsysinfo.collect.installed_packages       False\nsysinfo.collect.profiler                 False\nsysinfo.collect.locale                   C\nsysinfo.collect.per_test                 False\nsysinfo.collectibles.commands            /etc/avocado/sysinfo/commands\nsysinfo.collectibles.files               /etc/avocado/sysinfo/files\nsysinfo.collectibles.profilers           /etc/avocado/sysinfo/profilers\nrunner.output.colored                    True\nrunner.output.utf8                       \nremoter.behavior.reject_unknown_hosts    False\nremoter.behavior.disable_known_hosts     False\njob.output.loglevel                      debug\nrestclient.connection.hostname           localhost\nrestclient.connection.port               9405\nrestclient.connection.username           \nrestclient.connection.password           \nplugins.disable                          []\nplugins.skip_broken_plugin_notification  []\nplugins.loaders                          [\'file\', \'@DEFAULT\']\ngdb.paths.gdb                            /usr/bin/gdb\ngdb.paths.gdbserver                      /usr/bin/gdbserver\nplugins.jobscripts.pre                   /etc/avocado/scripts/job/pre.d/\nplugins.jobscripts.post                  /etc/avocado/scripts/job/post.d/\nplugins.jobscripts.warn_non_existing_dir False\nplugins.jobscripts.warn_non_zero_status  True\n\nAvocado Data Directories:\n\nbase     /builddir/avocado\ntests    /builddir/build/BUILD/avocado-63.0/examples/tests\ndata     /builddir/avocado/data\nlogs     /tmp/avocado_selftests.functional.test_basicURS8EB/job-2018-07-20T20.21-8283a8e\n\nNo variants available, using defaults only\n\nVariant :    /\nTemporary dir: /var/tmp/avocado_PcrpbP/avocado_job_Emy38k\n\nJob ID: 8283a8e84d1aa8c89f0501d06ce9e8cbaa4464f3\n\nINIT 1-examples/tests/simplewarning.sh\nPARAMS (key=timeout, path=*, default=None) => None\nTest metadata:\n  filename: /builddir/build/BUILD/avocado-63.0/examples/tests/simplewarning.sh\n  teststmpdir: /var/tmp/avocado_8P6hjz\n  workdir: /var/tmp/avocado_PcrpbP/avocado_job_Emy38k/1-examples_tests_simplewarning.sh\nSTART 1-examples/tests/simplewarning.sh\nDATA (filename=output.expected) => NOT FOUND (data sources: variant, file)\nRunning \'/builddir/build/BUILD/avocado-63.0/examples/tests/simplewarning.sh\'\n[stderr] /usr/bin/env: \xe2\x80\x98python\xe2\x80\x99: No such file or directory\nCommand \'/builddir/build/BUILD/avocado-63.0/examples/tests/simplewarning.sh\' finished with 127 after 0.00374507904053s\nExit status: 127\nDuration: 0.00374507904053\n\nReproduced traceback from: /builddir/build/BUILD/avocado-63.0/avocado/core/test.py:831\nTraceback (most recent call last):\n  File "/builddir/build/BUILD/avocado-63.0/avocado/core/test.py", line 1179, in test\n    self._execute_cmd()\n  File "/builddir/build/BUILD/avocado-63.0/avocado/core/test.py", line 1128, in _execute_cmd\n    raise exceptions.TestFail(details)\nTestFail\n\nLocal variables:\n -> self <class \'avocado.core.test.SimpleTest\'>: 1-examples/tests/simplewarning.sh\nDATA (filename=output.expected) => NOT FOUND (data sources: variant, file)\nDATA (filename=stdout.expected) => NOT FOUND (data sources: variant, file)\nDATA (filename=stderr.expected) => NOT FOUND (data sources: variant, file)\nFAIL 1-examples/tests/simplewarning.sh -> TestFail: \n\nTest results available in /tmp/avocado_selftests.functional.test_basicURS8EB/job-2018-07-20T20.21-8283a8e\n'
stderr: ''
----------------------------------------------------------------------
Ran 463 tests in 170.843s
FAILED (failures=1, skipped=36)
```
Here is the wrapped version of that long stdout line:
```
found extension EntryPoint.parse('teststmpdir = avocado.plugins.teststmpdir:TestsTmpDir')                                                                                       
found extension EntryPoint.parse('jobscripts = avocado.plugins.jobscripts:JobScripts')
found extension EntryPoint.parse('human = avocado.plugins.human:HumanJob')
found extension EntryPoint.parse('json_variants = avocado.plugins.json_variants:JsonVariants')                                                                                  
found extension EntryPoint.parse('yaml_to_mux = avocado_varianter_yaml_to_mux:YamlToMux')                                                                                       
found extension EntryPoint.parse('varianter_pict = avocado_varianter_pict:VarianterPict')                                                                                       
found extension EntryPoint.parse('json_variants = avocado.plugins.json_variants:JsonVariants')                                                                                  
found extension EntryPoint.parse('yaml_to_mux = avocado_varianter_yaml_to_mux:YamlToMux')                                                                                       
found extension EntryPoint.parse('varianter_pict = avocado_varianter_pict:VarianterPict')                                                                                       
found extension EntryPoint.parse('json_variants = avocado.plugins.json_variants:JsonVariants')                                                                                  
found extension EntryPoint.parse('yaml_to_mux = avocado_varianter_yaml_to_mux:YamlToMux')                                                                                       
found extension EntryPoint.parse('varianter_pict = avocado_varianter_pict:VarianterPict')                                                                                       
Command line: /builddir/.local/bin/avocado run --job-results-dir /tmp/avocado_selftests.functional.test_basicURS8EB --sysinfo=off examples/tests/simplewarning.sh --show-job-log
                          
Avocado version: 63.0                                     
                               
Config files read (in order):
/builddir/build/BUILD/avocado-63.0/avocado/etc/avocado/avocado.conf
/builddir/build/BUILD/avocado-63.0/avocado/etc/avocado/conf.d/resultsdb.conf
/builddir/build/BUILD/avocado-63.0/avocado/etc/avocado/conf.d/gdb.conf
/builddir/build/BUILD/avocado-63.0/avocado/etc/avocado/conf.d/result_upload.conf
/builddir/build/BUILD/avocado-63.0/avocado/etc/avocado/conf.d/jobscripts.conf
/builddir/.config/avocado/avocado.conf

Avocado config:
Section.Key                              Value
datadir.paths.base_dir                   /var/lib/avocado
datadir.paths.test_dir                   /usr/share/doc/avocado/tests
datadir.paths.data_dir                   /var/lib/avocado/data
datadir.paths.logs_dir                   ~/avocado/job-results
sysinfo.collect.enabled                  True
sysinfo.collect.commands_timeout         -1
sysinfo.collect.installed_packages       False
sysinfo.collect.profiler                 False
sysinfo.collect.locale                   C
sysinfo.collect.per_test                 False
sysinfo.collectibles.commands            /etc/avocado/sysinfo/commands
sysinfo.collectibles.files               /etc/avocado/sysinfo/files
sysinfo.collectibles.profilers           /etc/avocado/sysinfo/profilers
runner.output.colored                    True
runner.output.utf8
remoter.behavior.reject_unknown_hosts    False
remoter.behavior.disable_known_hosts     False
job.output.loglevel                      debug
restclient.connection.hostname           localhost
restclient.connection.port               9405
restclient.connection.username
restclient.connection.password
plugins.disable                          []
plugins.skip_broken_plugin_notification  []
plugins.loaders                          ['file', '@DEFAULT']
gdb.paths.gdb                            /usr/bin/gdb
gdb.paths.gdbserver                      /usr/bin/gdbserver
plugins.jobscripts.pre                   /etc/avocado/scripts/job/pre.d/
plugins.jobscripts.post                  /etc/avocado/scripts/job/post.d/
plugins.jobscripts.warn_non_existing_dir False
plugins.jobscripts.warn_non_zero_status  True

Avocado Data Directories:

base     /builddir/avocado
tests    /builddir/build/BUILD/avocado-63.0/examples/tests
data     /builddir/avocado/data
logs     /tmp/avocado_selftests.functional.test_basicURS8EB/job-2018-07-20T20.21-8283a8e

No variants available, using defaults only

Variant :    /
Temporary dir: /var/tmp/avocado_PcrpbP/avocado_job_Emy38k

Job ID: 8283a8e84d1aa8c89f0501d06ce9e8cbaa4464f3

INIT 1-examples/tests/simplewarning.sh
PARAMS (key=timeout, path=*, default=None) => None
Test metadata:
  filename: /builddir/build/BUILD/avocado-63.0/examples/tests/simplewarning.sh
  teststmpdir: /var/tmp/avocado_8P6hjz
  workdir: /var/tmp/avocado_PcrpbP/avocado_job_Emy38k/1-examples_tests_simplewarning.sh
START 1-examples/tests/simplewarning.sh
DATA (filename=output.expected) => NOT FOUND (data sources: variant, file)
Running '/builddir/build/BUILD/avocado-63.0/examples/tests/simplewarning.sh'
[stderr] /usr/bin/env: ‘python’: No such file or directory
Command '/builddir/build/BUILD/avocado-63.0/examples/tests/simplewarning.sh' finished with 127 after 0.00374507904053s                                                          
Exit status: 127
Duration: 0.00374507904053

Reproduced traceback from: /builddir/build/BUILD/avocado-63.0/avocado/core/test.py:831
Traceback (most recent call last):
  File "/builddir/build/BUILD/avocado-63.0/avocado/core/test.py", line 1179, in test
    self._execute_cmd()
  File "/builddir/build/BUILD/avocado-63.0/avocado/core/test.py", line 1128, in _execute_cmd                                                                                    
    raise exceptions.TestFail(details)
TestFail

Local variables:
 -> self <class 'avocado.core.test.SimpleTest'>: 1-examples/tests/simplewarning.sh
DATA (filename=output.expected) => NOT FOUND (data sources: variant, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, file)
FAIL 1-examples/tests/simplewarning.sh -> TestFail:

Test results available in /tmp/avocado_selftests.functional.test_basicURS8EB/job-2018-07-20T20.21-8283a8e                                                                       
```

This looks like more trouble arising from the use of `#!/usr/bin/env python`, but it's unclear to me how to resolve this one.

**Comment by clebergnu** [comment] 2018-07-20 21:07
Yes, this last one is clearly a different issue. So, let's keep this issue open, and possibly give #2723 and ack to get it out of the way.

**Comment by clebergnu** [comment] 2018-07-20 21:29
@mmathesius I think you're right about the cause of the failure.  `examples/tests/simplewarning.sh` calls a generic `avocado` command, which gets added to the path by the test code.  That generic `avocado` command is `scripts/avocado`, from the source tarball, which contains the unversioned `/usr/bin/env python`.

The fix should be something like:

```diff
$ git diff
diff --git a/selftests/functional/test_basic.py b/selftests/functional/test_basic.py
index 7b7edbad..1f26f9db 100644
--- a/selftests/functional/test_basic.py
+++ b/selftests/functional/test_basic.py
@@ -730,7 +730,9 @@ class RunnerSimpleTest(unittest.TestCase):
         simplewarning.sh uses the avocado-bash-utils
         """
         # simplewarning.sh calls "avocado" without specifying a path
-        os.environ['PATH'] += ":" + os.path.join(basedir, 'scripts')
+        # let's add the path that was defined at the global module
+        # scope here
+        os.environ['PATH'] += ":" + os.path.dirname(AVOCADO)
         # simplewarning.sh calls "avocado exec-path" which hasn't
         # access to an installed location for the libexec scripts
         os.environ['PATH'] += ":" + os.path.join(basedir, 'libexec')
```

**Comment by clebergnu** [comment] 2018-07-23 19:36
Closing as resolved.

**Closed by clebergnu** 2018-07-23 19:36 UTC
