### ISSUE TITLE
Will the avocado support the unittest's setUpClass and tearDownClass method?

### ISSUE THREAD

**Issue by linfenghuaster** [avocado-framework/avocado#1148] opened 2016-04-22 18:54 UTC
In virt test, sometimes, in order to save the test time, we want to set up the environment only once, and then run many cases. It is known that the method is setUpClass in unittest，but I can not find that the method in  avocado(0.34)?  Now, it is dodged by changing the core/runner.py files in my project. Is there a recommended way avoid the problem? Or the avocado will support setUpClass in the future? Thank you a lot!

**Comment by ldoktor** [comment] 2016-04-27 08:58
Hello @linfenghuaster, I'd say most probably not at this moment. One of the main feature of avocado is, that it separates each test into a different process to avoid influence of the preceding tests to the current test.

I'm not sure what is your primary goal, if setup some shared resources, you can do that inside job pre/post plugin.

Alternatively there is the Job API RFC https://www.redhat.com/archives/avocado-devel/2016-April/msg00014.html which might allow some shared class being passed between tests, but this is currently in the early stage (RFC pending).

Could you please share some details about your use case? If the Job API sounds useful, you can join the discussion and help shaping it.

Regards,
Lukáš

**Comment by linfenghuaster** [comment] 2016-05-04 17:16
Hello @ldoktor,  Thanks for you reply!  

The inside job pre/post plugin is for the job(may include many testsuites) but not for the testsuite, I don't know if I understood correctly?

In my situation, for example, one testsuite are made up of testcase1, testcase2 and testcase3. All the testcases need a running vm, in order to save the time, the setup of the running vm in testsuite  such as setUpClass will run only once instead of three times.

**Comment by ldoktor** [comment] 2016-05-05 11:33
Yes, I that's what I thought. This is currently not possible, maybe with the Job API. @clebergnu @adereis do you have any suggestions?

**Comment by ldoktor** [comment] 2016-08-15 08:24
This issue is traced in https://trello.com/c/Iw2acpiA/704-issue-will-there-be-a-support-for-setupclass and will be prioritized accordingly.

**Comment by linfenghuaster** [comment] 2016-09-07 16:03
@ldoktor Thanks, how is it going?

**Comment by ldoktor** [comment] 2016-09-07 16:23
@linfenghuaster it's not in the long-term list, but it's not yet scheduled in the sprint backlog, so I can't promise anything. If you depend on such feature it'd be best to send an RFC to the mailing list with a proposal and example usage. If you don't intend to work on it, you can try promoting this during the sprint release meeting, but our resources are quite limited. @clebergnu any chance the `Job API` addresses this issue? (if so that'd increase the priority of this issue)

**Comment by clebergnu** [comment] 2016-09-08 18:05
@linfenghuaster in fact those methods are present in an Avocado Test class:

```python
>>> from avocado import Test
>>> print Test.setUpClass
<bound method type.setUpClass of <class 'avocado.core.test.Test'>>
```

The issue is that our unittest compatibility is not complete, and we don't call those.  It'd be trivial to do so, *if* our runner design wasn't that different from the standard unittest runners.  Namely, we only load the class later in the execution, and do so on each test execution.  You can see how each test is run on its own process if you add this to your `setUp()` method:

```python
   def setUp(self):
       self.log.info("PID: %s", os.getpid())
```

That means that, while we could keep track of `setUpClass()` and `tearDownClass()` for a given test class, and only call them once, the effects of it could be limited to the first process only.

What I recommend, at least for now, is to try to write `setUp()` and `tearDown()` code that can check if a given state was set already set.  If your test setup is some kind of action that will last accross processes, say, installing a software package, you're pretty much covered here.  If you need to keep data within a class acrross test executions, you're out of luck, and  youwould have to resort to saving and restoring the data from an outside source (say a "pickle" file).

Altearnatively, the so called `Job API` could help, if you intend to set state that would apply to all your tests.

Can you better describe your use case so we can expand on this issue? Thanks!

**Comment by linfenghuaster** [comment] 2016-09-11 04:29
Thanks. I have not find a better way to resolve this so far,  and use the "pickle" way to avoid it.

**Comment by clebergnu** [comment] 2016-09-27 02:02
@linfenghuaster I'm closing this issue, since it's clear we can not achieve that level of compatibility with our test execution model.

This card:

https://trello.com/c/bN7w5Vzh/826-unittest-compatibility-document-process-model-and-class-setup-teardown-support

Will track adding this position and compatiblity support level to the official docs.

**Closed by clebergnu** 2016-09-27 02:02 UTC

**Comment by imphil** [comment] 2016-09-30 21:04
I don't want to hijack this bug, but I just came across the same or a similar problem and I think this use case fits in here.

I'm evaluating avocado to test an embedded system. Testing requires first compiling a piece of software, that flashing it onto the device in various ways and check the output. Essentially, this means
- download and compile the software *once*
- then have multiple `test*()` methods that use the software that was built, program it to the device and assert on various things.

The software build is what I would like to put in a per-class setup method, i.e. `setUpClass()`. Putting it in `setUp()` and thus recompiling it every time is not really efficient or safe, as the compilation might change (yet it hopefully does not) and skew the test results.

Right now I can live easily with a workaround (build inside `setUp()` and check a variable if the software was already compiled), but putting it into `setUpClass()` would be much more intuitive for most users familiar with unit test software.

I must admit, I don't understand how running the tests in different processes influences the implementation of a `setUpClass()` method, so I'll leave that discussion for the developers here :-)

**Comment by imphil** [comment] 2016-09-30 22:08
Further experimentation made me understand what was actually meant by the multiple processes, and how that influences the implementation of a `setUpClass()` method. My use case still stands, I'll leave it open therefore. Maybe, however, a more practical solution/workaround would be to register the output of the compilation somehow as asset and retrieve it for each test?

**Comment by ldoktor** [comment] 2016-10-05 09:03
Well unfortunatelly we don't have the JobAPI yet, but your situation looks like a good candidate for:

```
avocado run test_flash test_boots test_works ...
```
with dependency, which is not yet implemented. It should be available in the JobAPI, which is currently in RFC stage.

As for the setUpClass, yes, it can be implemented by the runner by pickling and injecting the object in the next test. The problem is it allows influencing other tests so we originally were against that, but we see that there are cases where it might be useful.

**Comment by TheMeaningfulEngineer** [comment] 2018-08-09 20:30
Hey, know this is an old thread but seems like addressing an issue I'm facing currently.
Also using avocado to test embedded systems and my tests run commands on the host to
be executed through the serial on the embedded device.

To be able to have everybody in the team contribute to writing tests they all have to 
written as simple tests.

For now I'm achieving execution ordering and by prepending the number in the file name.
For example:

```
tests/
    01_check_boot.py    
    02a_serial_login.py 
    02b_wifi_test.py
    03_facroty_rese.py
    04a_serial_login.py 
    04b_bt_test.py
```

I execute `avocado run tests` and the naming kind of does the job of dependencies.

@ldoktor You mention:

> Well unfortunatelly we don't have the JobAPI yet, but your situation looks like a good candidate for:
> 
>     avocado run test_flash test_boots test_works ...
> 
> with dependency, which is not yet implemented. It should be available in the JobAPI, which is currently in RFC stage.

What do dependencies mean in terms of your given example?
