### ISSUE TITLE
PIP based install from source fails on RHEL 8

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3462] opened 2020-01-08 14:47 UTC
Based on:

https://github.com/avocado-framework/avocado-vt/pull/2221/files#diff-0f7067c31caedf7df2739c9b07efa122R34

```
      # When installing from source, pip tries to install at
      # /usr/local/lib/python3.6/site-packages/ and fails with:
      # [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/test-easy-install-78.write-test'
      # workaround is to add "--prefix /"
```

Let's double check that this is an easy-install "condition" and file a bug in the appropriate place.

**Comment by beraldoleal** [comment] 2020-01-08 14:47
More information on our (deprecated) trello card:

https://trello.com/c/qj4tHbbp/1516-bug-pip-based-install-from-source-fails-on-rhel-8

**Comment by willianrampazzo** [comment] 2020-06-23 19:23
Is it still valid? I could not reproduce.

**Comment by clebergnu** [comment] 2020-08-04 15:32
Closing as there's no fix needed here, as explained in https://github.com/avocado-framework/avocado-vt/pull/2691

**Closed by clebergnu** 2020-08-04 15:32 UTC
Labels: bug
