### ISSUE TITLE
Is PyYAML 3.12 needs to be updated in the documentation ?

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#2695] opened 2018-06-28 11:03 UTC
```
# avocado variants -t  -m complex.yaml 
Error running method "initialize" of plugin "yaml_to_mux": '_BaseLoader' object has no attribute 'construct_python_str'
No variants available, using defaults only
```

**Comment by ldoktor** [comment] 2018-07-04 13:28
@narasimhan-v would you please provide more information about versions? I do have PyYAML 3.12 and it works well for me:

```
$ pip2 list | grep YAML
PyYAML (3.12)
$ avocado variants -m examples/yaml_to_mux/complex.yaml 
Multiplex variants (28):
Variant intel-scsi-workstation-20-12b3:    /run/os/distros/redhat/fedora/version/20, /run/os/distros/redhat/fedora/flavor/workstation, /run/hw/cpu/intel, /run/hw/disk/scsi
Variant intel-virtio-workstation-20-b322:    /run/os/distros/redhat/fedora/version/20, /run/os/distros/redhat/fedora/flavor/workstation, /run/hw/cpu/intel, /run/hw/disk/virtio
Variant amd-scsi-workstation-20-c523:    /run/os/distros/redhat/fedora/version/20, /run/os/distros/redhat/fedora/flavor/workstation, /run/hw/cpu/amd, /run/hw/disk/scsi
...
```

Ideally try running:

```
$ pip2 list 
$ AVOCADO_LOG_DEBUG=yes avocado --show all variants -m examples/yaml_to_mux/complex.yaml
```

**Comment by narasimhan-v** [comment] 2018-07-04 14:05
@ldoktor https://github.com/avocado-framework/avocado/blob/master/requirements-docs.txt has PyYAML 3.11, which does not work well with `construct_python_str`,
3.12 works just fine.

**Comment by mmathesius** [comment] 2018-07-05 15:06
For what it's worth, the Fedora `python-avocado` package builds recently started failing in Rawhide only (see https://apps.fedoraproject.org/koschei/package/python-avocado?collection=f29) with the same message while running self-tests:
```
AttributeError: '_BaseLoader' object has no attribute 'construct_python_str'
```
There is a full traceback of the exception included in the `build.log` linked from the above Koeschi page.

**Comment by ldoktor** [comment] 2018-07-10 13:20
@narasimhan-v would you please provide the output of the commands from https://github.com/avocado-framework/avocado/issues/2695#issuecomment-402479325 ? I'm not able to reproduce it with 3.10, 3.11, 3.12, 3.13b1, 3.13rc1, 3.13, 4.2b2, 4.2b4.

Anyway I am able to reproduce it with 4.2b1 so it looks like they had a breakage which should be fixed in the released version. Anyway we could update our requirements to avoid this version.

@mmathesius I tried clicking here and there, got to https://kojipkgs.fedoraproject.org/work/tasks/6062/27996062/build.log and yes, there is the same failure, but it uses `PyYAML 4.1`. This version is not available in pip but I assume it suffers the same issue as 4.2b1.

**Comment by ldoktor** [comment] 2018-07-10 13:33
I created https://github.com/avocado-framework/avocado/pull/2701 to explicitly ban the versions that did not worked for me, @narasimhan-v please let me know whether it changed anything.

**Comment by ldoktor** [comment] 2018-07-14 04:57
OK the non-working broken releases were blacklisted, please let us know if the problem persists...

**Closed by ldoktor** 2018-07-14 04:57 UTC
