### ISSUE TITLE
Inherited tests not being executed

### ISSUE THREAD

**Issue by TurboTurtle** [avocado-framework/avocado#4625] opened 2021-05-28 23:13 UTC
The sos project recently moved to avocado for our test framework, and we've noticed an interesting issue with regards to inherited tests.

First, here's our hierarchy for our test classes:

```
avocado.Test
        |
        V
BaseSoSTest
        |
        V
BaseSoSReportTest
        |
        V
StageOneReportTest  # Our test cases subclass this, several "global" tests are defined here
        |
        V
NetworkPluginTest  # For example, specific feature tests defined here
```

For reference, this is our basic directory layout:

```
tests/
|- sos_tests.py  # StageOneReportTest defined here
|- report_tests/
|  |- plugin_tests/
|     |- networking.py  # NetworkPluginTest defined here
|
|- vendor_tests/
|  |- redhat/
      |- rhbz1928628.py
```

Now, in `networking.py`, the tests defined in `StageOneReportTest` are inherited and executed by `NetworkPluginTest` as expected. However, the problem comes in `rhbz1928628.py`, which subclasses `NetworkPluginTest`. In this case, _only_ the tests defined in `rhbz1928628` are executed - none of the tests defined in the inheritance chain are executed.

[Our tests are defined here](https://github.com/sosreport/sos/tree/master/tests) for reference.

What is more interesting though (at least to me) though, is that we now have another PR which is adding another test under `tests/vendor_tests/redhat/` that subclasses `StageOneReportTest` directly, but we still get the same behavior - no execution of inherited tests. If you look at the [PR with the newly defined test](https://github.com/sosreport/sos/pull/2560) you can see it's not all that intricate, and not different from our approach in the tests defined under `tests/report_tests`, so it's interesting to see different behavior when subclassing the same `StageOneReportTest` just in different locations in the tree.

If you'd rather not pull and run the test suite yourself to see in action, here are the [logs from one of the test jobs](https://cirrus-ci.com/task/5921871758622720?logs=main#L186) from the above PR. If you do decide to run the tests yourself from the git repo, just note you'll need to set `PYTHONPATH=tests/` to get them to run successfully - otherwise you'll hit an import error.

Our CI jobs are currently configured to pull the latest release of avocado - we've seen this from version 84 through version 88.1.

Currently, I'm at a loss as to why we're seeing this behavior.

**Comment by willianrampazzo** [comment] 2021-05-31 11:17
I think this is the same reported here https://github.com/avocado-framework/avocado/issues/4611, isn't it?

**Comment by clebergnu** [comment] 2021-05-31 15:47
> I think this is the same reported here #4611, isn't it?

Yes, it is.  I've assigned myself to it.  @beraldoleal please don't take this wrong, but I'm closing #4611 because this issue has a bit more information and material to base my inquiry on.

**Comment by beraldoleal** [comment] 2021-05-31 15:53
@clebergnu I don't take it wrong, no problem here.

But even with more information here, IMO we could left the oldest one open, since the reference is already made. The information is not lost.

But no worries, just a nitpick comment.

**Comment by beraldoleal** [comment] 2021-05-31 15:55
Duplicate of #4611.

**Comment by clebergnu** [comment] 2021-06-18 20:36
@TurboTurtle please confirm that we're in sync wrt the expectations.  With the fix I'm working on, I've removed the `:avocado: enable` tags from the `tests/vendor_tests/redhat/rhbz1928628.py` file:

```diff
--- a/tests/vendor_tests/redhat/rhbz1928628.py
+++ b/tests/vendor_tests/redhat/rhbz1928628.py
@@ -17,7 +17,6 @@ class rhbz1928628(NetworkingPluginTest):
 
     https://bugzilla.redhat.com/show_bug.cgi?id=1928628
 
-    :avocado: enable
     :avocado: tags=stageone
     """
 
@@ -34,7 +33,6 @@ class rhbz1928628Enabled(NetworkingPluginTest):
     WARNING: it has been noted (via this rhbz) that certain NICs may pause
     during this collection
 
-    :avocado: enable
     :avocado: tags=stageone
     """
```

And then the output to my `avocado list tests/vendor_tests/redhat/rhbz1928628.py` command is:

```
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_eeprom_dump_not_collected
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_common_files_collected
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_ip_addr_symlink_created
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_forbidden_globs_skipped
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_archive_created
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_checksum_is_valid
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_no_new_kmods_loaded
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_archive_has_sos_dirs
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_manifest_created
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_html_reports_created
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_no_exceptions_during_execution
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628.test_no_ip_changes
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_eeprom_dump_collected
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_common_files_collected
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_ip_addr_symlink_created
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_forbidden_globs_skipped
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_archive_created
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_checksum_is_valid
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_no_new_kmods_loaded
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_archive_has_sos_dirs
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_manifest_created
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_html_reports_created
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_no_exceptions_during_execution
INSTRUMENTED tests/vendor_tests/redhat/rhbz1928628.py:rhbz1928628Enabled.test_no_ip_changes
```

Is that what you expected?

**Comment by TurboTurtle** [comment] 2021-06-18 20:38
@clebergnu yep - that is what we're looking for.

**Comment by clebergnu** [comment] 2021-06-18 21:21
> @clebergnu yep - that is what we're looking for.

Great, looks like the fix is effective:

https://cirrus-ci.com/task/4706731642060800?logs=main#L207

Sorry that it won't make into 89.0 (we have froze development for the Monday release) but will definitely be available early into the next development cycle.

**Closed** 2021-06-24 14:53 UTC
Labels: bug
