### ISSUE TITLE
Avocado crashed while running some tests

### ISSUE THREAD

**Issue by vssanchana** [avocado-framework/avocado#2332] opened 2017-12-07 09:24 UTC
**TEST 1:** /usr/bin/avocado run avocado-misc-tests/memory/transparent_hugepages.py --force-job-id 35a332caf32d6ec7c07bc9987fca61172c2cf303  --job-results-dir /home/shruvenk/
**JOB ID**     : 35a332caf32d6ec7c07bc9987fca61172c2cf303
**JOB LOG**    : /home/shruvenk/job-2017-12-07T03.39-35a332c.log
 (1/1) avocado-misc-tests/memory/transparent_hugepages.py:Thp.test:  
Avocado crashed: TestError: Unable to receive test's early-status in 60s, something wrong happened probably in the avocado framework.
**Traceback (most recent call last):**

  File "/usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/core/job.py", line 474, in run_tests
    execution_order)

  File "/usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/core/runner.py", line 616, in run_suite
    deadline):

  File "/usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/core/runner.py", line 398, in run_test
    test_status.wait_for_early_status(proc, 60)

  File "/usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/core/runner.py", line 166, in wait_for_early_status
    raise exceptions.TestError(msg)

**TestError**: Unable to receive test's early-status in 60s, something wrong happened probably in the avocado framework.

**JOB HTML**   : /home/shruvenk/job-2017-12-07T03.39-35a332c/results.html

**TEST 2** : /usr/bin/avocado run avocado-misc-tests/generic/ras.py --force-job-id 4f12916817b342b0e25feaf5d281f1de081821e8  --job-results-dir /home/shruvenk/
**JOB ID**     : 4f12916817b342b0e25feaf5d281f1de081821e8
**JOB LOG**    : /home/shruvenk/job-2017-12-07T03.46-4f12916.log
 (01/12) avocado-misc-tests/generic/ras.py:RASTools.test1_set_poweron_time: PASS (10.83 s)
 (02/12) avocado-misc-tests/generic/ras.py:RASTools.test2_sys_ident_tool: PASS (3.55 s)
 (03/12) avocado-misc-tests/generic/ras.py:RASTools.test3_lsmcode: PASS (12.60 s)
 (04/12) avocado-misc-tests/generic/ras.py:RASTools.test4_drmgr: PASS (450.66 s)
 (05/12) avocado-misc-tests/generic/ras.py:RASTools.test5_lsprop: PASS (78.81 s)
 (06/12) avocado-misc-tests/generic/ras.py:RASTools.test6_lsslot: PASS (120.51 s)
 (07/12) avocado-misc-tests/generic/ras.py:RASTools.test7_lsvio: PASS (17.62 s)
 (08/12) avocado-misc-tests/generic/ras.py:RASTools.test8_nvram: PASS (329.88 s)

Avocado crashed: TestError: Unable to receive test's early-status in 60s, something wrong happened probably in the avocado framework.
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/core/job.py", line 474, in run_tests
    execution_order)

  File "/usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/core/runner.py", line 616, in run_suite
    deadline):

  File "/usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/core/runner.py", line 398, in run_test
    test_status.wait_for_early_status(proc, 60)

  File "/usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/core/runner.py", line 166, in wait_for_early_status
    raise exceptions.TestError(msg)

**TestError**: Unable to receive test's early-status in 60s, something wrong happened probably in the avocado framework.

**JOB HTML**   : /home/shruvenk/job-2017-12-07T03.46-4f12916/results.html
[job-2017-12-07T03.46-4f12916.log](https://github.com/avocado-framework/avocado/files/1538453/job-2017-12-07T03.46-4f12916.log)
[job-2017-12-07T03.39-35a332c.log](https://github.com/avocado-framework/avocado/files/1538454/job-2017-12-07T03.39-35a332c.log)

**Comment by apahim** [comment] 2017-12-11 10:48
Not sure what's happening in your case, but Avocado creates a dedicated process to run the test in. If it takes 60s or more for that process to be created, you'll see that error message. When that happens, it usually means the system is so busy that it cannot even create a new process.

**Comment by ldoktor** [comment] 2017-12-13 14:48
Hello @vssanchana, this is unfortunate and hard to debug. Is this 100% reproducible, or only occasional would be my first question. I only have PowerNV machine so I can't really reproduce it.

Anyway would you please try applying this patch:

```diff
diff --git a/avocado/core/runner.py b/avocado/core/runner.py
index 1fb1abb..94fb42e 100644
--- a/avocado/core/runner.py
+++ b/avocado/core/runner.py
@@ -322,10 +322,15 @@ class TestRunner(object):
         # `multiprocessing.Process()`
         os.dup2(sys.stdin.fileno(), 0)
 
+        TEST_LOG.warning("Initializing test")
+
         instance = loader.load_test(test_factory)
         if instance.runner_queue is None:
             instance.set_runner_queue(queue)
         runtime.CURRENT_TEST = instance
+
+        TEST_LOG.warning("Getting early status")
+
         early_state = instance.get_state()
         early_state['early_status'] = True
         try:
@@ -333,6 +338,9 @@ class TestRunner(object):
         except Exception:
             instance.error(stacktrace.str_unpickable_object(early_state))
 
+        TEST_LOG.warning("Early_status pushed, waiting for 10s")
+        time.sleep(10)
+        TEST_LOG.warning("Starting the actual test")
         self.result.start_test(early_state)
         self.job._result_events_dispatcher.map_method('start_test',
                                                       self.result,
@@ -398,6 +406,7 @@ class TestRunner(object):
         cycle_timeout = 1
         time_started = time.time()
         signal.signal(signal.SIGTSTP, signal.SIG_IGN)
+        TEST_LOG.warning("Starting test thread.")
         proc.start()
         signal.signal(signal.SIGTSTP, sigtstp_handler)
         test_status.wait_for_early_status(proc, 60)
@@ -424,6 +433,7 @@ class TestRunner(object):
         result_dispatcher = self.job._result_events_dispatcher
 
         while True:
+            TEST_LOG.warning("TICK")
             try:
                 if time.time() >= deadline:
                     abort_reason = "Timeout reached"

```

to running Avocado (don't forget to `make deploy` or `make install` it afterwards) to get more details about the execution.

Additionally would you please look at `/var/log/messages` (or journalctl) for suspicious activity (like OOM killer, which, apart of test-bug, is the most common reason early_status was not pushed)?

**Comment by brianjmurrell** [comment] 2018-11-28 14:09
FWIW, I have just hit this issue.  It's really quite intermittent.  This is the first time in dozens of test runs since I started using Avocado.

Should we reopen this issue since it seems to be valid?

**Comment by clebergnu** [comment] 2018-11-28 14:17
@brianjmurrell definitely, yes.

**Comment by ldoktor** [comment] 2018-11-28 16:11
@brianjmurrell the previous attempt to fix failed on not-enough-data. Do you have more details or ideally a simpler reproducer? The code before sending early_status is fairly simple (unless one overrides the default `Test.__init__`.

**Comment by clebergnu** [comment] 2019-01-24 23:40
@brianjmurrell since there's no reproducer, let's close this again.

**Closed by clebergnu** 2019-01-24 23:40 UTC
