### ISSUE TITLE
A PKCS #11 module returned CKR_DEVICE_ERROR

### ISSUE THREAD

**Issue by will-Do** [avocado-framework/avocado#1112] opened 2016-04-06 10:20 UTC
When connect to an ovirt server by ovirtsdk API in avocado(only in avocado), it always fail as following error:
```
* About to connect() to X.X.X.X port 443 (#0)
* Trying X.X.X.X...
* Connected to X.X.X.X (X.X.X.X) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* Unable to initialize NSS database
* Initializing NSS with certpath: none
* NSS error -8023 (SEC_ERROR_PKCS11_DEVICE_ERROR)
* A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot.
* Closing connection 0
```
The expected result is like(connect ovirt outside avocado):
```
* About to connect() to X.X.X.X port 443 (#0)
* Trying X.X.X.X...
* Connected to X.X.X.X (X.X.X.X) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
...
```

The connect statements like:
```python
from ovirtsdk.api import API

url = XXX
username = XXX
password = XXX
api = API(url, username, password, insecure=True, debug=True)
```

**Comment by will-Do** [comment] 2016-04-06 10:29
The error thrown out by it curl when do NSS_InitContext , in lib/vtls/nss.c
```C
  if(cert_dir) {
    char *certpath = aprintf("sql:%s", cert_dir);
    if(!certpath)
      return CURLE_OUT_OF_MEMORY;

    infof(data, "Initializing NSS with certpath: %s\n", certpath);
    nss_context = NSS_InitContext(certpath, "", "", "", &initparams,
            NSS_INIT_READONLY | NSS_INIT_PK11RELOAD);
    free(certpath);

    if(nss_context != NULL)
      return CURLE_OK;

    infof(data, "Unable to initialize NSS database\n");
  }

  infof(data, "Initializing NSS with certpath: none\n");
  nss_context = NSS_InitContext("", "", "", "", &initparams, NSS_INIT_READONLY
         | NSS_INIT_NOCERTDB   | NSS_INIT_NOMODDB       | NSS_INIT_FORCEOPEN
         | NSS_INIT_NOROOTINIT | NSS_INIT_OPTIMIZESPACE | NSS_INIT_PK11RELOAD);
  if(nss_context != NULL)
    return CURLE_OK;

  infof(data, "Unable to initialize NSS\n");
  return CURLE_SSL_CACERT_BADFILE;
```

**Comment by apahim** [comment] 2016-04-06 14:48
I'm able to reproduce this issue. Working on that.

**Comment by apahim** [comment] 2016-04-06 19:44
@will-Do, both ovirt-python-sdk and yum (yum module is imported in avocado/utils/software_manager) are using `pycurl`. `pycurl` uses `libcurl`, that uses NSS as backend. The issue is a race condition is `libcurl` when both yum and ovirt need to use the `NSS_InitContext()`. I'm discussing with NSS folks how to fix and/or workaround it. So far the only way you can run your test without hitting this issue is by changing the `import yum` in `a/u/software_manager.py` to something that causes the exception... like `import yumm`. This will impact in the avocado `sysinfo` plugin, that will not have `yum` to use in the system report.

**Comment by will-Do** [comment] 2016-04-07 01:49
@apahim  Thanks for your replay, I will adjust our test to workaround this issue.

**Comment by apahim** [comment] 2016-04-07 17:13
@will-Do, nss folks were able to track this issue down and seems like they are going to consider a change in `NSS_InitContext()`, which should include a `SECMOD_RestartModules(PR_FALSE)` after a `fork()`. Anyway, they also provided a better workaround than the one I provided you. If you set the environment variable `NSS_STRICT_NOFORK` to `DISABLED` then the code is expected to work. It worked for me and I'd like to check if it works for you as well. Looking forward to see your results.

**Comment by will-Do** [comment] 2016-04-08 03:11
@apahim Cool, that works for me, thanks for your info.

**Comment by apahim** [comment] 2016-04-08 12:32
Great. Since this is a NSS issue, I will close this ticket. To follow up with NSS fix, please subscribe to this bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1317691.

**Closed by apahim** 2016-04-08 12:32 UTC
