### ISSUE TITLE
VM plugin: how is it working now? --vm-cleanup

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#396] opened 2015-02-03 11:42 UTC
Hi, 
I'm not sure how it is wokring now.
I've used virtual plugin like:
    sudo avocado run --vm --vm-domain checkmachine1-fedora-21-x86_64 --vm-clean --vm-username root --vm-password testvm --vm-hostname 192.168.122.2 --xunit out2.xml compiletest.sh checklogin.py

and it seems that it creates new snapshot, althought old one is leaved there. I saw in virt-manager, that there are stored snapshot (host is RHEL7)
Is it intended or it is a bug?
It cause that using this param is very very slow.
On fedora21 it works better, but I dont know If it is caused by avocado or by bug in libvirt
    Regards
    Honza

**Comment by ruda** [comment] 2015-03-05 13:59
Hi @jscotka ,

that's correct, it creates a new snapshot before performing any test copy and execution, do the tests, then it restores the vm to the previous snapshot being created (and destroy the snapshot). We make use of libvirt to perform operations on VMs.

Note that If this feature is leaving the snapshot behind after test execution, then yes, it's a bug. But it don't touch on previous snapshot created (from other sources), so it will leave them alone, In this case, this is not a bug, but the expected behavior.

My experience with this plugin is from Fedora 20 and Fedora 21, running on a machine with SDD disk, so it's fast, just a few seconds and it don't leave any snapshot behind.

**Comment by clebergnu** [comment] 2015-08-10 18:53
@jscotka FIY this issue is now fixed. Hope you can try it and have good results. If not, please let us know.

**Closed by clebergnu** 2015-08-10 18:53 UTC

**Comment by jscotka** [comment] 2015-08-11 07:33
Hi,
thanks for that. I'll see if it works as I expected.
     Honza
