### ISSUE TITLE
colors of terminal multiplied for each testcase (terminal output)

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#833] opened 2015-10-09 09:35 UTC
Hi,
I've tested recent avoicado from COPR repo and I've seen output what is done to console, but I've stored it to file, and there are multiplied COLOR chars for each test:
:: [  BEGIN   ] :: Running 'sudo -u test bash -c 'export DISPLAY=:99; avocado run ./selenium-login.py''
JOB ID     : 922db57926a1a120ac4449361a17d2ecc8988b46
JOB LOG    : /home/test/avocado/job-results/job-2015-10-09T05.26-922db57/job.log
TESTS      : 3
 (1/3) ./selenium-login.py:BasicTestSuite.testBase:  [1D-[1D\[1DPASS (2.61 s)
 (2/3) ./selenium-login.py:BasicTestSuite.testLogin:  [1D|[1D/[1D-[1D\[1DPASS (4.42 s)
 (3/3) ./selenium-login.py:BasicTestSuite.testLoginChangeTabNetworking:  [1D|[1D/[1D-[1D\[1D|[1D/[1D-[1D\[1D|[1D/[1DPASS (13.51 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TIME       : 20.54 s

It is not blocing issue, but in case of thousand of testecases it can cause bigger troubles.
avocado version: 0.29.0-1.el7.centos

   Regards
   Honza

**Comment by ldoktor** [comment] 2015-10-09 19:26
Hello Jan,

what exactly is the problem? When you run avocado interactively in terminal (with terminal support) it displays the `throbber`, which is the little rotating `-`. You can see it in the output, first test run <3s and has `-\` in the output. The second test run <5s and has `|/-\` in the output. What you don't see in the output is the `\b` character, which removes the previous character and overwrites it. So it seems that your terminal doesn't support the `\b` and keeps all of the char in the output.

Can you give us the environment? What terminal do you use, is it run through some logging server (beaker?) and what do you actually expect? One way to avoid using throbber (and fancy colors) is to use `TERM=none avocado run ...`.

**Comment by lmr** [comment] 2015-10-09 19:31
The problem is that we seem to be accumulating color sequence codes on each label:

1) 1st test: 1 sequence
2) 2nd test: 2 sequences
3) 3rd test: 3 sequences

This seems to be an actual bug.

**Comment by lmr** [comment] 2015-10-09 19:33
Hmmm, or this is simply the throbber, like you suggested, and this is not a bug. Now I'm curious as to how to reproduce this.

**Comment by lmr** [comment] 2015-10-09 19:39
Yep, nevermind my first comment, sorry:

    MOVE_BACK = '\033[1D'
    MOVE_FORWARD = '\033[1C'

This is clearly throbber output that got recorded into his output. @jscotka, you should use the trick @ldoktor proposed

    export TERM=none; scripts/avocado run passtest

So that we can close this issue.

**Comment by jscotka** [comment] 2015-10-13 08:50
Hi,
thanks for explanation. I've missed that it is rotating char, not coloring. I had fear that I found  the bug :-)

**Closed** 2015-10-13 09:34 UTC
