### ISSUE TITLE
""avocado list --vt-type qemu --help""  command breaks terminal

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado#1260] opened 2016-06-13 10:17 UTC
Hi.
Command : avocado list --vt-type qemu --help

breaks terminal

After it my terminal becomes unusable:

`
[root@spice-bkr02 cfg]# [root@spice-bkr02 cfg]# [root@spice-bkr02 cfg]# [root@spice-bkr02 cfg]# [root@spice-bkr02 cfg]# [root@spice-bkr02 cfg]# [root@spice-bkr02 cfg]# [root@spice-bkr02 cfg]# [root@spice-bkr02 cfg]#`

**Comment by ldoktor** [comment] 2016-06-13 10:22
Hello Andrey, would you please provide some details? I'm unable to reproduce this with the latest master fdbbd3bacc073d2abc172828ce90cb04fd2175ce using `xterm` as terminal (I even tried `ctrl+c` while waiting for response).

**Comment by ldoktor** [comment] 2016-06-13 10:40
OK, I'm able to reproduce this, but on invalid input:

```
avocado list --foo
```

For now please use `stty echo` to re-enable echo and we'll take care of this issue.

**Comment by ldoktor** [comment] 2016-06-13 10:47
https://trello.com/c/F1x0ZUye/727-bug-avocado-list-foo-disables-echo

**Comment by apahim** [comment] 2016-06-30 11:48
@Andrei-Stepanov this was merged and it's expected to fix the issue:
https://github.com/avocado-framework/avocado/commit/55efdca9f005b9b4f497b840b5cee19ac543f29e
If you have a chance to test it, please let me know if it works for you.

**Comment by ldoktor** [comment] 2016-08-15 08:23
Hello @Andrei-Stepanov the problem seem fixed now. If you still see this issue, please reopen this issue with a reproducer.

**Closed by ldoktor** 2016-08-15 08:23 UTC
