### ISSUE TITLE
[NRunner] State machine do not detect test abort.

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4255] opened 2020-10-05 20:51 UTC
The NRunner state machine is not detecting an aborted test to finish its execution.

Steps to reproduce:

```avocado run --test-runner=nrunner examples/tests/abort.py```

The expected behavior is Avocado finishing after some seconds, but Avocado keeps executing and never ends:

```
$ avocado run --test-runner=nrunner examples/tests/abort.py
JOB ID     : 1ab074459a059aa0fbaafc66303ddf181c09f4da
JOB LOG    : /home/wrampazz/avocado/job-results/job-2020-10-05T17.46-1ab0744/job.log
 (1/1) examples/tests/abort.py:AbortTest.test: STARTED
```

**Comment by willianrampazzo** [comment] 2020-10-06 17:35
One more detail I noticed. If I do a small change to the test and sleep for 3 seconds, the legacy runner will consider the `timeout` attribute. The next runner is not considering that.

Example:

```
$ cat examples/tests/abort.py
import os

from avocado import Test


class AbortTest(Test):

    """
    A test that just calls abort() (and abort).

    :avocado: tags=failure_expected
    """

    timeout = 2.0

    def test(self):
        import time
        time.sleep(3)

$ avocado run examples/tests/abort.py 
JOB ID     : 5eb5c1a1e42bffa16c1f2e500e5293762db8eb46
JOB LOG    : /home/wrampazz/avocado/job-results/job-2020-10-06T14.27-5eb5c1a/job.log
 (1/1) examples/tests/abort.py:AbortTest.test: INTERRUPTED: Test interrupted by SIGTERM\nRunner error occurred: Timeout reached\nOriginal status: ERROR\n{'name': '1-examples/tests/abort.py:AbortTest.test', 'logdir': '/home/wrampazz/avocado/job-results/job-2020-10-06T14.27-5eb5c1a/test-results/1-examples_tests_abort.p... (2.07 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 1 | CANCEL 0
JOB HTML   : /home/wrampazz/avocado/job-results/job-2020-10-06T14.27-5eb5c1a/results.html
JOB TIME   : 2.61 s

$ avocado run --test-runner=nrunner examples/tests/abort.py 
JOB ID     : 4b085e699dab82521cb36e88eb118f70acf83780
JOB LOG    : /home/wrampazz/avocado/job-results/job-2020-10-06T14.32-4b085e6/job.log
 (1/1) examples/tests/abort.py:AbortTest.test: STARTED
 (1/1) examples/tests/abort.py:AbortTest.test: PASS (3.02 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/wrampazz/avocado/job-results/job-2020-10-06T14.32-4b085e6/results.html
JOB TIME   : 4.27 s
```

The second run should also have been interrupted.

And maybe, this should be a separate issue?

**Comment by clebergnu** [comment] 2020-10-06 17:43
Yes @willianrampazzo the timeout support is certainly a separate issue.

**Comment by willianrampazzo** [comment] 2020-10-06 17:47
> Yes @willianrampazzo the timeout support is certainly a separate issue.

Okay, thanks, I can think that it is still not supported, and not necessarily a bug. I'll open a new issue.

**Comment by richtja** [comment] 2020-10-08 13:21
>> Yes @willianrampazzo the timeout support is certainly a separate issue.
>
> Okay, thanks, I can think that it is still not supported, and not necessarily a bug. I'll open a new issue.

@clebergnu, @willianrampazzo I did some testing here and  I think that these two issues are connected. 

When I run the legacy runner without timeout the runtime is 10 seconds which is the default timeout for dead processes. If I delete this default timeout the legacy runner behaves same as nrunner.  I think that the problem is that the nrunner doesn't have default timeouts.

```
$ cat examples/tests/abort.py
import os

from avocado import Test


class AbortTest(Test):

    """
    A test that just calls abort() (and abort).

    :avocado: tags=failure_expected
    """


    def test(self):
        os.abort()

avocado run  examples/tests/abort.py 
JOB ID     : 6399aeb6be2bdb0e976a027411cd1fd42a6297d3
JOB LOG    : /home/jarichte/avocado/job-results/job-2020-10-08T15.19-6399aeb/job.log
 (1/1) examples/tests/abort.py:AbortTest.test: ERROR: Test died without reporting the status. (10.18 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/jarichte/avocado/job-results/job-2020-10-08T15.19-6399aeb/results.html
JOB TIME   : 10.73 s

```

**Comment by richtja** [comment] 2020-11-12 10:35
I am closing this because it is connected with #4257

**Closed by richtja** 2020-11-12 10:35 UTC
Labels: bug, nrunner
