### ISSUE TITLE
Default log file for nrunner based tests

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4804] opened 2021-07-26 22:04 UTC
Users will most of the time rely on a predictable log file for tests.  For instance, as of #4781, that information is available in ``results.json``.  Example:

```
$ avocado run --json - /bin/true 
{
    "cancel": 0,
    "debuglog": "/home/cleber/avocado/job-results/job-2021-07-26T17.58-0509ac4/job.log",
    "errors": 0,
    "failures": 0,
    "interrupt": 0,
    "job_id": "0509ac4ea5601da8ecd035aff0c951b011a57a1e",
    "pass": 1,
    "skip": 0,
    "tests": [
        {
            "end": 2404102.343587384,
            "fail_reason": null,
            "id": "1-/bin/true",
            "logdir": "/home/cleber/avocado/job-results/job-2021-07-26T17.58-0509ac4/test-results/1-_bin_true",
            "logfile": "/home/cleber/avocado/job-results/job-2021-07-26T17.58-0509ac4/test-results/1-_bin_true/debug.log",
            "start": 2404102.330324509,
            "status": "PASS",
            "tags": {},
            "time": 0.01326287491247058,
            "whiteboard": ""
        }
    ],
    "time": 0.01326287491247058,
    "total": 1,
    "warn": 0
}
```

The relevant line being:

```
            "logfile": "/home/cleber/avocado/job-results/job-2021-07-26T17.58-0509ac4/test-results/1-_bin_true/debug.log",
```

But when using the nrunner we get:

```
           "logfile": "<unknown>",
```

Besides the setting of the value, it's probably a good idea to have a generic, catch all log file for every single test, even if it's a link to another log file.

---

This is part of #4802

**Comment by richtja** [comment] 2021-07-27 09:16
Hi @clebergnu the reason why the logfile is `<unknown>` for `/bin/true` test is that this test didn't log anything and the log file wasn't created, I don't see a problem here. Can you please give some example of what you expect as a result when the test doesn't have logs?

**Comment by clebergnu** [comment] 2021-07-27 14:26
> Hi @clebergnu the reason why the logfile is `<unknown>` for `/bin/true` test is that this test didn't log anything and the log file wasn't created, I don't see a problem here. Can you please give some example of what you expect as a result when the test doesn't have logs?

Not really.  Check for instance:

```
$ avocado run --test-runner=nrunner --json - /bin/uname
{
    "cancel": 0,
    "debuglog": "/home/cleber/avocado/job-results/job-2021-07-27T10.25-43a19a6/job.log",
    "errors": 0,
    "failures": 0,
    "interrupt": 0,
    "job_id": "43a19a67718fe5742332eafe10c1c135f90ae0ed",
    "pass": 1,
    "skip": 0,
    "tests": [
        {
            "end": 2463287.770584658,
            "fail_reason": "<unknown>",
            "id": "1-/bin/uname",
            "logdir": "/home/cleber/avocado/job-results/job-2021-07-27T10.25-43a19a6/test-results/1-_bin_uname",
            "logfile": "<unknown>",
            "start": 2463287.757894023,
            "status": "PASS",
            "tags": {},
            "time": 0.012690634932368994,
            "whiteboard": "<unknown>"
        }
    ],
    "time": 0.012690634932368994,
    "total": 1,
    "warn": 0
}
```

While we do have a `/home/cleber/avocado/job-results/job-2021-07-27T10.25-43a19a6/test-results/1-_bin_uname/stdout` containing `Linux`.

**Comment by richtja** [comment] 2021-07-27 15:31
> > Hi @clebergnu the reason why the logfile is `<unknown>` for `/bin/true` test is that this test didn't log anything and the log file wasn't created, I don't see a problem here. Can you please give some example of what you expect as a result when the test doesn't have logs?
> 
> Not really. Check for instance:
> 
> ```
> $ avocado run --test-runner=nrunner --json - /bin/uname
> {
>     "cancel": 0,
>     "debuglog": "/home/cleber/avocado/job-results/job-2021-07-27T10.25-43a19a6/job.log",
>     "errors": 0,
>     "failures": 0,
>     "interrupt": 0,
>     "job_id": "43a19a67718fe5742332eafe10c1c135f90ae0ed",
>     "pass": 1,
>     "skip": 0,
>     "tests": [
>         {
>             "end": 2463287.770584658,
>             "fail_reason": "<unknown>",
>             "id": "1-/bin/uname",
>             "logdir": "/home/cleber/avocado/job-results/job-2021-07-27T10.25-43a19a6/test-results/1-_bin_uname",
>             "logfile": "<unknown>",
>             "start": 2463287.757894023,
>             "status": "PASS",
>             "tags": {},
>             "time": 0.012690634932368994,
>             "whiteboard": "<unknown>"
>         }
>     ],
>     "time": 0.012690634932368994,
>     "total": 1,
>     "warn": 0
> }
> ```
> 
> While we do have a `/home/cleber/avocado/job-results/job-2021-07-27T10.25-43a19a6/test-results/1-_bin_uname/stdout` containing `Linux`.

I see, so we have to decide when the log file is `log.debug`, `stdout` or `stderr`. So what about instead of `logfile` use a list `logfiles` with paths to all of those which were created?

**Comment by clebergnu** [comment] 2021-07-27 16:16
I have mixed feelings about replacing `logfile` with `logfiles`, because:

1. it will break the recently added "interface"
2. it won't add the information about what is **the primary** test log file

I believe there's value to having a predictable test log file.  For instance, after running a test job, doing something like:

```
grep my_pattern ~/avocado/job-results/latest/test-results/*/debug.log
```

Instead of:

```
grep my_pattern ~/avocado/job-results/latest/test-results/*/*
```

Because of false positive matches with, say, the `whiteboard` or any other file that is not necessary a log file.  The alternative of looking into the `logfiles` fields, makes it too complex for regular command line usage.  In short, because of the "by test type" kind of logging we're doing with the `nrunner` we lost the ability to always rely on `debug.log`.

**Comment by richtja** [comment] 2021-07-28 12:24
Maybe I will need more explanations, are you proposing to create `debug.log` as the primary test log file even if it will be empty? IMO it will be confusing for users. As an example, we can use the `/bin/uname` where user will have empty `debug.log` and all logs will be in `stdout`.

We also can create some primary test log file which will contains everything from `debug.log`, `stdout` and `stderr`. Then the user will have a possibility to use the primary log file or use just the specific one. But if we use such solution, IMO we won't need the `debug.log`, `stdout` and `stderr` files anymore.

**Comment by pevogam** [comment] 2021-08-05 15:03
Hi @richtja, I am not sure I fully understand you here. At least at the moment `debug.log` already contains `stderr` and (unconfirmed atm but) it used to contain `stdout` lines for the stdout. So in a way it already plays the role of a standard all-containing test log file and I would advise everyone to keep this avocado-age-old file and naming at least for VT and other tests.

A lot of the users (us included) have various result analysis scripts and others that make use of the debug.log file and dropping or changing the debug.log will be a lot of breakage and potential headaches for everyone that has already learned this behavior. It is best if whatever changes are done on the inside don't affect the general usage of the software on the outside where users constantly have to learn new behaviors.

**Comment by richtja** [comment] 2021-08-06 09:09
Hi @pevogam 

> Hi @richtja, I am not sure I fully understand you here. At least at the moment `debug.log` already contains `stderr` and (unconfirmed atm but) it used to contain `stdout` lines for the stdout. So in a way it already plays the role of a standard all-containing test log file and I would advise everyone to keep this avocado-age-old file and naming at least for VT and other tests.

On the nrunner is not true, the `debug.log` only contains output form avocado loggers and the `stdout` or `stderr` are inside different files.

> 
> A lot of the users (us included) have various result analysis scripts and others that make use of the debug.log file and dropping or changing the debug.log will be a lot of breakage and potential headaches for everyone that has already learned this behavior. It is best if whatever changes are done on the inside don't affect the general usage of the software on the outside where users constantly have to learn new behaviors.

That is exactly my proposal to create primary log file with all the information and as you sad the best way will be to use `debug.log` for it. Actually, I started discussion #4816 about this topic, where you can find more info.

**Comment by richtja** [comment] 2021-08-06 09:13
It looks like github doesn't link issues with discussions when the issue is mentioned. So you can find the discussion about this topic in #4816.

**Comment by pevogam** [comment] 2021-08-09 07:09
> > Hi @richtja, I am not sure I fully understand you here. At least at the moment `debug.log` already contains `stderr` and (unconfirmed atm but) it used to contain `stdout` lines for the stdout. So in a way it already plays the role of a standard all-containing test log file and I would advise everyone to keep this avocado-age-old file and naming at least for VT and other tests.
> 
> On the nrunner is not true, the `debug.log` only contains output form avocado loggers and the `stdout` or `stderr` are inside different files.

Hmmm, then maybe I missed something because on all my failing tests (now using nrunner) I can see the same error message + stack trace in both stderr and the debug.log. I guess the ones in the debug.log originate from some other source than the stderr then.

> It looks like github doesn't link issues with discussions when the issue is mentioned. So you can find the discussion about this topic in #4816.

I see.

**Closed** 2021-08-25 12:14 UTC
Labels: bug, nrunner
