### ISSUE TITLE
Change in settings processing order

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado#3950] opened 2020-06-20 13:12 UTC
Hello guys,

with the future_settings the processing order of params changed, which does not work for Avocado-vt. Avocado-vt requires parsed settings (which is why the `SettingsDispatcher` was located elsewhere and there are big fat warnings under `avocado.core.dispatcher`:

```
Besides the dispatchers listed here, there's also a lower level
dispatcher that these depend upon:
:class:`avocado.core.settings_dispatcher.SettingsDispatcher`
```

Anyway, currently during `Avocado-vt` import the `data_dir.get_data_dir()` returns always the default (`/var/lib/avocado/...`) instead of the value defined in `config`. (took me a while and several spoiled machines to find out why it's writing to a different location). Avocado-vt really requires the datadir early in the initialization phase which is why the dispatcher and parsing used to happen earlier.

**Comment by ldoktor** [comment] 2020-06-20 13:13
^^ To test this you can add a breakpoint in `avocado-vt` in `virttest.data_dir` around line `36` where the early `data_dir.get_data_dir()` happens.

**Comment by ldoktor** [comment] 2020-06-20 13:15
^^ Also note that the `avocado config --datadir` reports the right value, the difference is time when this call happens (Avocado-vt - during import, config - after config parsing)

**Comment by clebergnu** [comment] 2020-06-22 15:18
Hi @ldoktor, I can reproduce your issue, and I think it will soon become a non-issue.  The reason is that we're planning to eliminate the configuration files on Avocado (not the support to read them).  So, the Avocado-VT provided configuration files (which are added to the list of configuration files by the new settings module) would be naturally respected.  You can try this out simply by removing your `$SOURCE_ROOT/avocado/avocado/etc/avocado/avocado.conf`.  I did that, an added a `vt_mine.conf` containing:

```
[datadir.paths]
data_dir = /tmp/data
```

And the result is:

```
$ avocado config --datadir
Config files read (in order, '*' means the file exists and had been read):
    * /home/cleber/src/avocado/avocado-vt/avocado_vt/conf.d/vt_mine.conf
    * /home/cleber/src/avocado/avocado-vt/avocado_vt/conf.d/vt.conf
    * /home/cleber/src/avocado/avocado-vt/avocado_vt/conf.d/vt_joblock.conf
      /home/cleber/src/avocado/avocado/avocado/etc/avocado/avocado.conf
      /etc/avocado/avocado.conf

Avocado replaces config dirs that can't be accessed
with sensible defaults. Please edit your local config
file to customize values

Avocado Data Directories:
    base     /home/cleber/avocado
    tests    /home/cleber/src/avocado/avocado/examples/tests
    data     /tmp/data
    logs     /home/cleber/avocado/job-results
    cache    /tmp/data/cache
```

I'm working on the Avocado-VT right now, with the goal of making it also support `future.settings` on all occurrences it needs to get the configuration values, while keeping support for the current settings (for 69.x LTS support).  Once that is done, we'll remove the configuration files from Avocado itself and this issue should go away IIUC.

Let me know if it makes sense to you.

**Comment by clebergnu** [comment] 2020-06-22 16:01
Besides that, there's still one thing to consider on the future settings.  If the `data_dir` functions are to be dynamic, and respect new configuration files added *after* `settings = Settings()` is done on `avocado.core.future.settings`, something like this would be necessary:

```diff
diff --git a/avocado/core/data_dir.py b/avocado/core/data_dir.py
index 842ecce84..6c1efefaa 100644
--- a/avocado/core/data_dir.py
+++ b/avocado/core/data_dir.py
@@ -61,6 +61,7 @@ def _get_settings_dir(dir_name):
     Returns a given "datadir" directory as set by the configuration system
     """
     namespace = 'datadir.paths.{}'.format(dir_name)
+    future_settings.merge_with_configs()
     path = future_settings.as_dict().get(namespace)
     return os.path.abspath(path)
 
@@ -205,6 +206,7 @@ def get_cache_dirs():
     """
     Returns the list of cache dirs, according to configuration and convention
     """
+    future_settings.merge_with_configs()
     cache_dirs = future_settings.as_dict().get('datadir.paths.cache_dirs')
     datadir_cache = os.path.join(get_data_dir(), 'cache')
     if datadir_cache not in cache_dirs:
```

Or, on the Avocado-VT side:

```diff
diff --git a/virttest/data_dir.py b/virttest/data_dir.py
index 1031540c3..5c2db6190 100755
--- a/virttest/data_dir.py
+++ b/virttest/data_dir.py
@@ -12,6 +12,7 @@ import stat
 
 from avocado.core import data_dir
 from avocado.core.settings import settings
+from avocado.core.future.settings import settings as future_settings
 from avocado.utils import distro
 from avocado.utils import path as utils_path
 
@@ -31,6 +32,9 @@ if (os.path.isdir(_DEFAULT_SHARED_PATH) and
 else:
     _ROOT_PATH = os.path.realpath(os.path.dirname(os.path.dirname(__file__)))
 
+
+future_settings.merge_with_configs()
+
 ROOT_DIR = os.path.abspath(_ROOT_PATH)
 BASE_BACKEND_DIR = os.path.join(ROOT_DIR, 'backends')
 DATA_DIR = os.path.join(data_dir.get_data_dir(), 'avocado-vt')
```

@ldoktor a different point, but related to this.  It seems to me that with Avocado *not* providing configuration files anymore, and thinking of Avocado-VT as a plugin (Avocado itself will always be available) do you see any problems with dropping the `Settings` plugins and just moving the Avocado-VT configuration files to *Avocado*'s configuration file directory? Say `/etc/avocado/conf.d/vt.conf` like when it's installed from packages or the equivalent in tree?

If the `Settings` plugin is dropped, and the configuration file order is one that depends, say, on the lexicographical order, then even this dynamic diff mentioned here would not be necessary.

@ldoktor @beraldoleal does it make sense to you?

**Comment by beraldoleal** [comment] 2020-06-22 16:13
@clebergnu makes more sense to me to have this on the avocado-vt side, instead of calling every time the functions are called.

**Comment by sathnaga** [comment] 2020-07-29 08:35
@clebergnu this is still failing in current master, good to have this fixed soon, tnx!
let me know incase of any help needed here.

**Comment by sathnaga** [comment] 2020-07-29 08:37
I vote for Avocado-vt side fix .

**Comment by sathnaga** [comment] 2020-08-04 15:20
@ldoktor @clebergnu can we get this addressed, master still hitting with this annoying issue. tnx in advance.

**Comment by pevogam** [comment] 2020-11-03 23:13
Is this issue still truly open? I think we detected some troubles matching this description before releasing and fixed them already.

**Comment by beraldoleal** [comment] 2021-09-01 19:37
IIUC, @richtja did a great working porting avocado-vt to use the next runner and this is not an issue anymore. I will close this but please, feel free to reopen if needed.

**Closed by beraldoleal** 2021-09-01 19:37 UTC
